### ISSUE TITLE
Need customer details mandatory option

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-Bugs#101]
I want to be able to make it mandatory to enter customer info so we don't forget that part when checking a customer in

**Comment by Repair-Desk** [comment]
@aishahanif we need to add this check on **_invoice, ticket and POS section_**

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk can you prepare a quick FS document before end of next week?

**Comment by Repair-Desk** [comment]
@jeffsand8243 do you think this will suffice?

![mandatory](https://cloud.githubusercontent.com/assets/21986026/21214455/a5957dd0-c2bc-11e6-82ff-32300cff2933.png)

**Comment by jeffsand8243** [comment]
Yes that's should be good!

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday

**Comment by Uzair-RepairDesk** [comment]
We added triggers to make customer details mandatory while creating a repair ticket or invoice.

**Customer Details Mandatory trigger while creating Repair Ticket**
You can go to [Settings > Module Configurations > Repairs > Enable "Admin/Employee must add customer information before booking a repair job"](https://app.repairdesk.co/index.php?r=config/repairs)

**Customer Details Mandatory trigger while creating Invoice**
You can go to [Settings > Module Configurations > Invoices > Enable "Admin/Employee must add customer information before creating an invoice"](https://app.repairdesk.co/index.php?r=config/invoice)

Check screenshots attached
![uzairshah invoice config](https://user-images.githubusercontent.com/22955861/40901224-ba02bf9e-67e8-11e8-9429-7878d9c278ee.png)
![uzairshah repairs config](https://user-images.githubusercontent.com/22955861/40901225-ba2e5b90-67e8-11e8-81cb-3f1be5260fe4.png)
