### ISSUE TITLE
Be able to Delete a GRN. Also have a cancel button to cancel creating a GRN

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-Bugs#104]
Be able to delete created GRN's.
When creating a new one be able to cancel creating it instead of only having a save button.

**Comment by Repair-Desk** [comment]
@muhammadfayyaz3 have you made any progress on this one?

**Comment by Uzair-RepairDesk** [comment]
@afrahm 
We have added cancel button on creating GRN. Please review at your end.
Regarding delete GRN functionality, its not possible to give the option because its dependent on PO and inventory is also updated against GRN.
I hope it helps
