### ISSUE TITLE
Cannot update description field for 'Sell Your Device Widget'

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#105]
Hey Guys,

Please Go to Settings > Integrations >Language Editor > Edit (English) > Sell Your Device Widget. I am using a Super SU account to update. When Clicking 'Save All' nothing happens, even after multiple tries at once. 

We need to update in this area ASAP.

RD displays content updated as soon as the page is loaded.

![language editor](https://cloud.githubusercontent.com/assets/22953208/20199688/2780c866-a7f8-11e6-905f-98be629b895e.jpg)

**Comment by Repair-Desk** [comment]
@HafizAnas can you please look into this at your convenience

**Comment by Repair-Desk** [comment]
@aishahanif When you edit default language (english) and hit save all nothing happens. It should display a loader and shows changes has been saved.

**Comment by Repair-Desk** [comment]
@TechnologyTraders We apologize for inconvenience. At present RD doesn't allow you to edit default language.

**Comment by TechnologyTraders** [comment]
@Repair-Desk We know RD doesn't allow us to edit default languages, so when will this be fixed? Is it going to be fixed?

**Comment by Repair-Desk** [comment]
@TechnologyTraders Now you can edit default language & translate Sell your device or other modules according to your business requirements  :)
