### ISSUE TITLE
Self Check In Widget - Suggested Improvements

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#106]
It would be great if we can display all information on one page so the customers can fill out an easy and straight forward information page, with their contacts phone, address, email, pass code, device, model and then sign terms.

![walk in](https://cloud.githubusercontent.com/assets/21986026/20199769/bead5332-a7ce-11e6-8473-8b29b31fb140.png)

There should be a trigger as well that allows you to switch off/hide **network or device issue field** in case we would like to enter it manually.

**Comment by Repair-Desk** [comment]
@imiamran please take a look at this one please to see if its possible to update workflow

**Comment by Repair-Desk** [comment]
@itskamran can you have imran get it done in December release

**Comment by Repair-Desk** [comment]
@itskamran what's the status on this one?

**Comment by itskamran** [comment]
@Repair-Desk 

It's working fine on Staging server and will be verifies again once mam Aisha Hanif make it live after 25.

**Comment by HafizAnas** [comment]
@Repair-Desk 
Your requested changes has been done.
