### ISSUE TITLE
Wrong Total against Old Invoice

### ISSUE THREAD

**Issue by HafizAnas** [Repair-DeskPOS/RepairDesk-Bugs#107]
Once I create Invoice with 50% discount and make full payment. Later if I open this invoice/order from POS again through view invoice button.

it shows wrong Total amount. (See Screenshot)

![old calculation-issue1](https://cloud.githubusercontent.com/assets/22954115/20205999/33b0d840-a7ff-11e6-82bd-e6f8ec5c34a0.png)
![old calculation-issue2](https://cloud.githubusercontent.com/assets/22954115/20206001/33b74306-a7ff-11e6-998f-995d8361e9a0.png)
![old calculation-issue3](https://cloud.githubusercontent.com/assets/22954115/20206002/33bbc20a-a7ff-11e6-8345-9ce03d205638.png)

**Comment by itskamran** [comment]
Issue has been resolved.
