### ISSUE TITLE
Issue with Reports (Stats)

### ISSUE THREAD

**Issue by HafizAnas** [Repair-DeskPOS/RepairDesk-Bugs#108]
@muhammadfayyaz3 
 There is something wrong when I refund discount item/Ticket.
I make a Ticket with two items one is 35$ and 2nd one is 100% (use part against 2nd item cost price is 25$) and give 50% inline discount on 2nd one.

Total is 85 and make payment, later I refund this repair order, that display wrong stats. In location Sale by item type and Location Daily sales display almost correct amount. But there is something in wrong in main stats (See Screenshots)

![stats issue incase of repair order refund](https://cloud.githubusercontent.com/assets/22954115/20214858/83d84cb2-a832-11e6-805a-e71cdcc7d03d.png)

![stats issue incase of repair order refund1](https://cloud.githubusercontent.com/assets/22954115/20214890/b0c451e4-a832-11e6-83df-4744b11829ff.png)

**Comment by Repair-Desk** [comment]
@HafizAnas @itskamran what's the progress on this one?

**Comment by itskamran** [comment]
@Repair-Desk It is to be discussed between development team tommorow and than it will be finished on priority basis. Thanks

**Comment by HafizAnas** [comment]
Dear @muhammadfayyaz3 
Issue has been fixed.
