### ISSUE TITLE
Order Now - Hyperlink on purchase order

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#109]
For special orders sometimes staff enter **eBay, amazon or product link in description.** It would be great if it shows **_"CLICK HERE TO ORDER"_** on purchase order listing so the manager / owner doesn't have to open each PO manually.

![po](https://cloud.githubusercontent.com/assets/21986026/20226023/2dd719e8-a868-11e6-8469-3ed9fdb829d1.png)

**Comment by aishahanif** [comment]
@HafizAnas enhancement is complete and live on staging please review

**Comment by Repair-Desk** [comment]
When you view purchase order it doesnt display link as hyperlink **(see attached)**

![hyperlink](https://cloud.githubusercontent.com/assets/21986026/20313175/e5bad132-ab77-11e6-8755-f192a65e158f.png)

It still doesn't say Order now on Purchase order listing page

**Comment by Repair-Desk** [comment]
@muhammadfayyaz3 is it deployed on live?
