### ISSUE TITLE
Post Device Repair Condition - 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#114]
When you save post device repair condition and hit save nothing happens.

![firstcall velachery view ticket](https://cloud.githubusercontent.com/assets/21986026/20421533/5b1c5c10-ad86-11e6-8917-8874b1a9cd8c.png)

**Comment by HafizAnas** [comment]
@Repair-Desk 
I have reviewed, it's working fine and I am not able to reproduce it. Please have a look attach screenshots.

![post-condition1](https://cloud.githubusercontent.com/assets/22954115/20474157/fcc54e70-afe6-11e6-8c5e-d54c43ffafe2.png)

![post-condition2](https://cloud.githubusercontent.com/assets/22954115/20474174/1068fa3a-afe7-11e6-8dc3-b92a0b1955de.png)


![post-condition3](https://cloud.githubusercontent.com/assets/22954115/20474182/17f976bc-afe7-11e6-9924-c9fe93cb1632.png)

**Comment by Repair-Desk** [comment]
Thanks @HafizAnas its working now
