### ISSUE TITLE
Popup to create invoice on ticket has OK/Cancel instead of Yes/No

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-Bugs#115]
When you save a ticket that doesn't have an invoice, it asks if you want to create one. The popup has two buttons (OK or Cancel). These should be Yes or No, as it is sometimes a little confusing for staff.

<img width="588" alt="screen shot 2016-11-19 at 10 46 05 am" src="https://cloud.githubusercontent.com/assets/1414304/20451493/b36845fe-ae45-11e6-89e8-b5227ee7662a.png">

**Comment by Repair-Desk** [comment]
@afrahm Sorry for the confusion.

I believe you should use trigger under **settings << module configuration << tickets**  that stops you from creating repair ticket whenever it is updated **(see attached)** 

![create invoice](https://cloud.githubusercontent.com/assets/21986026/20465432/c6ffdc3c-af7e-11e6-97c5-f819b3f52804.png)

**Comment by afrahm** [comment]
OK thanks. So that will stop that popup?

Even still it should say Yes/No not OK/Cancel

**Comment by Repair-Desk** [comment]
@afrahm That will certainly stop pop up.
