### ISSUE TITLE
Add part on ticket

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#117]
@HafizAnas Can you check following scenario

If charge tax on repair cost trigger is enabled.

On edit ticket page when I add a new part or change a part on repair in the ticket section will it accurately change the tax amount?

**Comment by HafizAnas** [comment]
When I change Tax class of part on Ticket edit page, System display NaN against Tax and Cost field, where as it should be amount in figure.

![tax-nan](https://cloud.githubusercontent.com/assets/22954115/20471836/a1a2bf7e-afd6-11e6-9729-6952d112a753.png)

**Comment by imiamran** [comment]
we added this functionality on on POS . it will not changed overall ticket tax if changed from parts

**Comment by itskamran** [comment]
Issue has been resolved. Thanks
