### ISSUE TITLE
Offline Credit Card Option should be in the list of Payment Methods

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#118]
@muhammadfayyaz3 
We updated the concern of offline credit card option, however from that update few customers are not able to view "Offline Credit Card" option in the Payment Method and Checkout list. 
Can you please execute a query to check where its missing and make sure its should be display in the payment method list and checkout page as well. 
Please make sure that it should not be duplicated.

**Comment by muhammadfayyaz3** [comment]
@Uzair-RepairDesk All done
