### ISSUE TITLE
Cannot order PO

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#119]
PO is not sorted. It used to sort from latest to oldest. but now it doesn't sort. It's very hard to find the PO now. Can you check this issue. 

![screen shot 2016-11-21 at 5 19 28 pm](https://cloud.githubusercontent.com/assets/22993605/20472550/bc1fabe0-b00e-11e6-9950-29321bb0c668.png)

**Comment by HafizAnas** [comment]
Hi @quangc 
Sorry for inconvenience, Let me check at our end.

**Comment by HafizAnas** [comment]
Hi @quangc, 
your reported issue has been fixed. Please confirm at your end and do let me know if youstill have any question.

**Comment by quangc** [comment]
This closed issue has been reappeared again, please fix it as last time?

**Comment by HafizAnas** [comment]
Hi @quangc 
Sorry for inconvenience, Let me check and revert back to you.

**Comment by Repair-Desk** [comment]
@HafizAnas what's the status on this one?

**Comment by itskamran** [comment]
Issue has been resolved. Thanks
