### ISSUE TITLE
Label not printing with barcode.

### ISSUE THREAD

**Issue by itskamran** [Repair-DeskPOS/RepairDesk-Bugs#120]
Upon creating a trade-in the label does not print with bar code automatically. If I manually print via printnode after the tradein is created then it prints with the barcode.

**- Capalaba Admin | Capalaba Store**

**Comment by Uzair-RepairDesk** [comment]
@HafizAnas 
Can you please confirm this from Sir @imiamran and test it from Cabalaba account. If issue persists please assign it to sir imran to get it fixed.

**Comment by Uzair-RepairDesk** [comment]
@HafizAnas 
Customer has given approval to use his account . You can test this one with Sir @imiamran  in our 2nd half (after the business hours of Australia)

**Comment by jeffsand8243** [comment]
I have same issue and I have to save the trade in twice before it prints

**Comment by Repair-Desk** [comment]
@jeffsand8243 I believe the issue has been fixed. Can you double check on your end?

**Comment by jeffsand8243** [comment]
I believe it is fixed! Thank you!

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday
