### ISSUE TITLE
RD does not show the number of trade-ins when viewing a customer

### ISSUE THREAD

**Issue by itskamran** [Repair-DeskPOS/RepairDesk-Bugs#123]
RD does not show the number of trade-ins when viewing a customer, any customer. It shows the headings: Total, Repairs, Unlocks, Accessories & Parts, Casual, and Trade-in. _**But it does not show us if there are any trade-ins by that customer. It just shows up as 0.**_

**Capalaba Admin | Capalaba Store**

**Comment by Uzair-RepairDesk** [comment]
We need screenshot for this to proceed. I have asked them on Intercom

**Comment by Uzair-RepairDesk** [comment]
Its working fine. Enhancement needed to also view the trade in value for a customer who sell the device. Customer is updated on Intercom that he can share the idea on user community page and we can deal it once we update customers module.
