### ISSUE TITLE
VAT Tax issues on previous Invoices

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#124]
Dear Sir @imiamran 
One of our customer Peter from "Foxfones Repairs" reported the following issues:-
1: If order is open from the previous invoice "2320", the price of "iPad Mini Digitiser replacement is "84.99" but somehow it displays price "85" (Please check with Miss @aishahanif is this issue is because of rounding issues.
2: The same item is tax inclusive item, it i change the price of item, it doesn't calculate correctly and make the tax exclusive with price. 

**Can we get it fixed ASAP.**

If you find any queries/concerns, You can also ask @HafizAnas regarding this. You can take login credentials of customer from me or Anas as well.

**Comment by Uzair-RepairDesk** [comment]
@HafizAnas
Once you review this on staging server please make sure that you also review this same issue with following scenario:-
"If we change the value to Zero (because we may not want to charge the customer) it calculates VAT amount of £4 or £5 something like that"

**Comment by foxfones** [comment]
Please also check that when putting a zero value in that there is no VAT calulated

**Comment by Uzair-RepairDesk** [comment]
Peter @foxfones 
Your reported issue has been fixed. if you change the price on previous invoice with Tax (VAT) inclusive item. It doesn't make it exclusive now and its also working fine in case of 0 value.

Please review at your end. Please do let me know if further assistance required. Thanks
