### ISSUE TITLE
PO Not Sorted

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#127]
Hi team, the PO are still not sorted. We brought this issue up a few days ago, it was said to be resolved. But it still occur at the moment. Please review this issue 
![screen shot 2016-11-21 at 5 19 28 pm](https://cloud.githubusercontent.com/assets/22993605/20612130/c7dbd874-b30a-11e6-91d2-3105c75c97d4.png)

**Comment by Repair-Desk** [comment]
@quangc can you elaborate

**Comment by quangc** [comment]
The Purchase Order Screen used to display in descending order with the newest order come first. But lately, it doesnt. It doesn't display based on any order. There is no sorting function as well so the PO screen display everything randomly
![screen shot 2016-11-25 at 2 46 47 pm](https://cloud.githubusercontent.com/assets/22993605/20614063/468aaf98-b31e-11e6-9e12-67626fa96e47.png)

**Comment by HafizAnas** [comment]
Hi @quangc 
I am really sorry for this trouble again. we will fix this issue asap

**Comment by Uzair-RepairDesk** [comment]
Hey @quangc 
Your reported issue has been fixed. Please verify at your end. Thanks
