### ISSUE TITLE
POS Repair Price

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#128]
On POS screen, Repair price cannot be change.
For example, in this case we set the price to be $180
![price](https://cloud.githubusercontent.com/assets/22993605/20638109/85e2f358-b3f0-11e6-995d-8154066c6952.png)
but then, it doesn't use that price but change back to the original price which is $120
![price 2](https://cloud.githubusercontent.com/assets/22993605/20638118/ad585ad6-b3f0-11e6-8130-6ffa1dc359b9.png)

**Comment by Repair-Desk** [comment]
**Hi @quangc** 

We sincerely apologize for inconvenience. We believe the issue has been fixed already. Please log out, clear browser cache and try again.

Please do let us know if the error persist.
