### ISSUE TITLE
Unable to scan/type in job number tickets on the POS system 

### ISSUE THREAD

**Issue by iCellsouthcity** [Repair-DeskPOS/RepairDesk-Bugs#129]
![image](https://cloud.githubusercontent.com/assets/23712887/20644439/1ebc5fd0-b499-11e6-801c-96450be60072.png)

When we scan the ticket on the POS system it come up with the following message as in the screenshot, this really needs to be fixed fast because when customer buy accessories at the same time they do a repair we have to go into the ticket and add the items from there which is time consuming.

**Comment by Repair-Desk** [comment]
@iCellsouthcity We apologize for inconvenience. I will ask one of our developer to look into this.

In the meantime you can manually enter Ticket ID, add accessories to order and checkout.

**Comment by Repair-Desk** [comment]
@HafizAnas Can you please look into this

**Comment by iCellsouthcity** [comment]
Thanks the problem is sorted! 👍

**Comment by Repair-Desk** [comment]
@iCellsouthcity Glad its working for you now!!
