### ISSUE TITLE
Total Prices for products not been set right by the system. 

### ISSUE THREAD

**Issue by iCellsouthcity** [Repair-DeskPOS/RepairDesk-Bugs#135]
![new](https://cloud.githubusercontent.com/assets/23712887/20741038/881a76de-b72c-11e6-84dc-2fbfc0f0ea29.jpg)

Our retail price for a screen is $130.00 and the system as you can see on the ticket above is say that its $98.30 and if we add the GST amount the system say which is $14.74 this will make the total price for the screen repair $98.30+$14.74 = $113.04
Where as it should have been Screen price + GST = $130.00

If you add the tow GST values on the system as you can see on the screen shot above which are $14.74+$2.61 = $17.35
But the system is showing that the total for the GST value should be $19.57 there is a $2.22 of a difference in the GST value. 
Some customer think we are over charging them.

**Comment by HafizAnas** [comment]
Hi @iCellsouthcity,
Sorry for Inconvenience. Let me check at our end and revert back to you soon.

**Comment by itskamran** [comment]
Issue has been resolved. Thanks
