### ISSUE TITLE
The price for repair changes once we edit signature after creating the job.

### ISSUE THREAD

**Issue by iCellsouthcity** [Repair-DeskPOS/RepairDesk-Bugs#136]
![new](https://cloud.githubusercontent.com/assets/23712887/20741441/096c4486-b72f-11e6-94a5-16b44bca3ce9.jpg)

![new](https://cloud.githubusercontent.com/assets/23712887/20741462/2a2f3228-b72f-11e6-8f0b-397edf005aae.jpg)

Once we have created a job on the POS system and if we need to edit the customer signature the ticket changes the repair prices as soon as the customer enters the signature. So if we save the ticket without changing the price back to the original we have to come back in to the ticket to edit the price in order to charge the customer. This issue is slowing us down alot as we are taking the signature on an iPad.

**Comment by Repair-Desk** [comment]
@iCellsouthcity 

I'm sorry about issue with the price. While we are working on fixing this issue you can use customer facing display integration tp display order details & save customer’s signature on a work order using an iPAD.

You can check out how you can setup customer facing display at the link here: 
**https://repairdesk.uservoice.com/knowledgebase/articles/1102397-how-to-configure-customer-facing-display**

If you have any other questions, just let me know and I’ll be happy to help. 

Thanks

**Comment by itskamran** [comment]
Dear @iCellsouthcity,

Issue has been resolved. Kindly check and let us know. Thanks
