### ISSUE TITLE
Unable to edit discount on total bill if we edit discount per product. 

### ISSUE THREAD

**Issue by iCellsouthcity** [Repair-DeskPOS/RepairDesk-Bugs#137]
![new](https://cloud.githubusercontent.com/assets/23712887/20741727/fd4c9910-b730-11e6-9bed-46e3b19830d0.jpg)

![new](https://cloud.githubusercontent.com/assets/23712887/20741769/2d30e8de-b731-11e6-8237-f92c1ff71a8b.jpg)

When add a discount to the total bill and then if we have to give more discount just for an individual product the discount that we gave for the total bill disappears. When we have to give like 10% off on a bill and still give more discount on a specific product because we need the customer to see that we have given them multiple discounts this kind of makes it impossible.

**Comment by HafizAnas** [comment]
Hi @iCellsouthcity,
Sorry for Inconvenience. Currently our system support only one discount type at a time, either you can give overall discount or Inline discount.
Like once you give over all discount then you are not able to give individual discount against specific item.
