### ISSUE TITLE
Ticket from one store location doesn't show in other location

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#14]
please refer to the below attached images.

![](https://cloud.githubusercontent.com/assets/21986026/19551885/e92f0182-96c6-11e6-8b6d-df5c264b0293.png)

![](https://cloud.githubusercontent.com/assets/21986026/19551886/e92f9638-96c6-11e6-8b3d-83c4bfea0c15.png)

**Comment by HafizAnas** [comment]
@aishahanif Please have a look this issue again.

**Comment by aishahanif** [comment]
@HafizAnas @hafeezshahid  fix is on staging please review

**Comment by HafizAnas** [comment]
Issue has been fixed on Staging please do it live and let me know once you will live.
