### ISSUE TITLE
Payroll date range feature

### ISSUE THREAD

**Issue by Jamal-repairdesk** [Repair-DeskPOS/RepairDesk-Bugs#140]
One of our client **Reece Baldwin from Elite Repairs** wants to add payroll feature in Repair Desk that allow administrator to mark time sheet as paid between certain dates. 

His employees get payed on Friday and he would like to start the new week on Saturday.

**Comment by Uzair-RepairDesk** [comment]
We have developed payroll functionality. Information is available in following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1849522-how-to-setup-payroll-for-employees
