### ISSUE TITLE
System not recognizing the bar codes for some products.

### ISSUE THREAD

**Issue by iCellsouthcity** [Repair-DeskPOS/RepairDesk-Bugs#142]
![1](https://cloud.githubusercontent.com/assets/23712887/20863465/f7436e8e-ba2f-11e6-92c9-f4b694840e6c.jpg)

![2](https://cloud.githubusercontent.com/assets/23712887/20863482/267030e8-ba30-11e6-863a-1678a4d1060b.jpg)

When we scan some items on POS the system does not recognize the bar-code even though its been correctly entered in the inventory and the following error message pops up.

**Comment by Repair-Desk** [comment]
@HafizAnas Can you check this at your convenience?

**Comment by Repair-Desk** [comment]
@iCellsouthcity 

**Show on POS** trigger was switched off which stopped the item to display on POS.

![trigger](https://cloud.githubusercontent.com/assets/21986026/20872823/8ef9a642-bac3-11e6-96fb-340e50b2eb5d.png)

**Comment by Repair-Desk** [comment]
@HafizAnas if the trigger is disabled and if you search for a product admin should still be able to add this line item to register

**Comment by Repair-Desk** [comment]
@itskamran can you assign it to imran so he can fix?

**Comment by itskamran** [comment]
@Repair-Desk Already assigned to imran for tommorow. Thanks

**Comment by HafizAnas** [comment]
@iCellsouthcity 
Your reported issue has been fixed. Kindly verify at your end and do let me know if you have any question.
