### ISSUE TITLE
Email invoice / receipt on POS

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#143]
When you create repair ticket or hit checkout it would be great if you have a button that says email invoice which opens up a pop up window to enter customer email and notes (just like invoice section)

![email](https://cloud.githubusercontent.com/assets/21986026/21050736/4e38d06e-be3e-11e6-9d13-b95b8edadc9b.png)

**Comment by Repair-Desk** [comment]
@itskamran can we add this in December release

**Comment by HafizAnas** [comment]
@RepairDeskPOS 

Your requested changes has been done. kindly verify at your end.
