### ISSUE TITLE
HTML Issue

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#144]
Hey. Could you ask them to fix the issue when entering customer info that when you press tab it goes down to number instead of last name. I have seen other request this as well and it should be super easy and fast to fix. It is just very annoying to have to go click on last name instead of being able to tab over to last name after entering first name.

**Comment by Repair-Desk** [comment]
@itskamran can you ask sajjad to fix this one please

**Comment by HafizAnas** [comment]
@RepairDeskPOS 
Your reported issue has been fixed.
