### ISSUE TITLE
System gets slow and freezes and crashes 

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-Bugs#147]
Please make software faster and more reliable

**Comment by Repair-Desk** [comment]
@jeffsand8243 We have recently updated RepairDesk database and optimize queries which has improved software speed. 

FYI we will continue to improve software speed during the next 2 months so you can expect it to be faster and more reliable

**Comment by jeffsand8243** [comment]
Ok sounds good! Glad you guys are working hard on it! Keep up the good work!

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday
