### ISSUE TITLE
Fix issue with a search resetting every time you edit or delete a listing

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-Bugs#150]
On payroll and in inventory search when you enter specific search criteria and pull up results when you edit any of the search results or delete a listing it returns you to the unfiltered presearch starting point. This is very time consuming and annoying when you need to edit several things in the same search field and you have to reser the search criteria after ever change to an item or employee. Please fix!

**Comment by Repair-Desk** [comment]
@itskamran  This is important. Can we look into this please?

**Comment by Uzair-RepairDesk** [comment]
@jeffsand8243 
If you apply search filter on inventory or services, pull up the results and update item/service. It doesn't return to unfiltered pre-search starting point. It keeps the search criteria same. Can you please check again at your end?
On Payroll and time sheet, it certainly needs to be updated and I will ask the development team to do the needful.

**Comment by HafizAnas** [comment]
Hi @jeffsand8243,
your reported issue has been fixed. Kindly verify at your end and do let us know if you have any question.
