### ISSUE TITLE
Add current profit calculation  display to each ticket

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-Bugs#151]
Other repair softwares have a sidebar next to each ticket internal view that shows cost total and profit. That would be nice so we can make sure each ticket is making a good profit.

**Comment by Repair-Desk** [comment]
@jeffsand8243 I believe it will be a nice add-on. Do you know where should we display overall profit since a repair ticket can have multiple line items?

**Comment by Repair-Desk** [comment]
@jeffsand8243 What are your thoughts on this:

![screenshot](https://cloud.githubusercontent.com/assets/21986026/21053883/27846a28-be4d-11e6-85e4-d5e76635fd20.png)

**Comment by jeffsand8243** [comment]
Hi. That looks good! Thanks for working on my ideas!

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday

**Comment by HafizAnas** [comment]
Hi @jeffsand8243 

Your requested changes has been end. Kindly check at your end and do let us know if you have any question. I am going to close this ticket for now.

Thanks!
