### ISSUE TITLE
Make employees have to login with pin before use 

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-Bugs#153]
Have system auto log out employees after a few minutes of inactivity and have a pop up screen that forces them to login with pin before using software again so no one can use the software using another employees login or name and it will show who does what in the software.

**Comment by Repair-Desk** [comment]
@jeffsand8243 I believe you should enable this trigger **"Employee should enter access pin before each sale transaction"** here: https://app.repairdesk.co/index.php?r=config/pos

**Comment by jeffsand8243** [comment]
Hi. Yes. I do this already. And that is good for  ringing up customers. But I was thinking it would be better if this login box popped up automatically after a few minutes of inactivity so that everything that each employee does would be under their login instead of someone else's who was still logged in when the other user got on the computer. Do you understand?

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday

**Comment by RepairDeskPOS** [comment]
Thanks for your feedback and we have added it to our roadmap. You will be notified once its added to RepairDesk

**Comment by ibroken** [comment]
Yes great idea 
I would say even 60 sec of software not being used 
As if your a manager and walk away from the pos it great to know that a sales rep can just go a view cost and or edit inventory..

**Comment by jeffsand8243** [comment]
60 second logout would be good

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday
