### ISSUE TITLE
IMEI / Serial number character length ON POS & tickets page

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#156]
Cannot input long serial numbers as there is a limit on characters. Some desktop computers has serial number that is greater than 15 digit.

![imei](https://cloud.githubusercontent.com/assets/21986026/21050475/ba78b1e2-be3c-11e6-8552-75b030fe678a.png)

**Comment by HafizAnas** [comment]
@Repair-Desk 
Your requested changes has been done.
