### ISSUE TITLE
Unable to enlarge uploaded pre/post repair images

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#157]
We cannot enlarge uploaded pictures which is very important for warranty checks

![enlarge image](https://cloud.githubusercontent.com/assets/21986026/21050594/682285ca-be3d-11e6-9225-54cdba045674.png)

**Comment by HafizAnas** [comment]
@Repair-Desk 
Your reported issue has been fixed.
