### ISSUE TITLE
Import Inventory Issue

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#160]
When you import Repairs/Accessories CSV for the first time you have to go to each Manufacturer and enable trigger **"SHOW ON POS"** or the products doesn't appear on POS. 

It should be done automatically as a lot of new customers doesn't know how it works.

Also if a manufacturer / device doesn't contain an item it doesn't allow you to delete it

**Comment by itskamran** [comment]
Dear All,
Issue is fixed and reviewed. Ticket is going to be closed now. Thanks
