### ISSUE TITLE
Repair Tracker - Last Name In Arabic

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#163]
If you enter customer last name in Arabic to find repair ticket it doesn't work

**Comment by itskamran** [comment]
Issue has been resolved. Kindly check screenshot. Thanks

![fixtag 8 ticket](https://cloud.githubusercontent.com/assets/23633903/21254846/0c4b7854-c38a-11e6-8278-6fda5e248bd3.png)

**Comment by Repair-Desk** [comment]
@itskamran @HafizAnas 

Can you also check on **Repair Tracker** (see attached)

![image](https://cloud.githubusercontent.com/assets/21986026/21256849/8d147cae-c396-11e6-8334-84c1639bcbdf.png)

**Comment by HafizAnas** [comment]
@Repair-Desk 
Your reported issue has been fixed.
