### ISSUE TITLE
PrintNode only prints one label for multiple devices on the same repair ticket

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#164]
RepairDesk only prints the 1st device label listed on the repair ticket. Even if we view the repair ticket and manually print via PrintNode it only prints the 1st device label. We then have to manually print through the PDF viewer and can only select one device at a time even though it offers a check box for all devices. Please fix this ASAP as it is a disruption to business.

**Comment by Fazal-RepairDesk** [comment]
@TechnologyTraders 
Just wanted to update you about the issue. We've verified from you account and it is working fine. 

May be there is an issue with your printer which doesn't allow you to print 2nd page or there is some issue with its setting. But we have tested it twice and it's working fine by using our printers on your account. 

The following labels are generated from your account on our printer. 
![technologytraders_printnode_label_rd tested_2](https://cloud.githubusercontent.com/assets/22954033/21386989/6a570222-c797-11e6-9d82-5fa037144683.jpg)
