### ISSUE TITLE
Update Clock In / Out Issue

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#168]
Dear Kamran

Can you ask fayyaz to check this issue.

It doesn't show update Clock In / Out button. Please fix it asap

**Reported by Jeff "the smartphone medics" Andrew "kixup repair"**

**Here is the screenshot:**

![image](https://cloud.githubusercontent.com/assets/21986026/21257680/39b632d2-c39b-11e6-9ec6-1e02da7ae1ee.png)

**Comment by muhammadfayyaz3** [comment]
Issue Fixed

**Comment by HafizAnas** [comment]
@Repair-Desk 
Your reported issue has been fixed.
