### ISSUE TITLE
Employee Roles Cost Price + Employee Location

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#17]
1. User has assigned a superuser account the role of manager. However the manager cannot see the Cost Price anymore.
"We have created a Manager Role which is Super User and assign a user into this Role but seem that account cannot access Cost Price."
Although I have confirmed the customer login details I'm unable to login. Please check into that as well. 
2. Customer tried to update location for staff and the system shows it as saved but it reverts back to the previous ones. The reason is perhaps that when the employee is logged in at the time so the location doesn't get updated till he has logged off. The system should show the user as logged in so that he can log off for the updates to take effect. 

Quang's Email:
"Hi Fazal,

I just want to bring up the old issues that not been fixed yet. Please have someone looks into this for us. There are few Trade In items created from one store shows up in other stores.

As below screenshots, the Springvale and Frankston both have same Trade In item 1676."
<img width="1135" alt="quang_1" src="https://cloud.githubusercontent.com/assets/22954033/19554986/5a8a4046-96d4-11e6-8de7-b99f442e0cd2.png">
<img width="1111" alt="quang_2" src="https://cloud.githubusercontent.com/assets/22954033/19554987/5aa2c274-96d4-11e6-8d2a-833a4cbe9baa.png">

**Comment by muhammadfayyaz3** [comment]
Issue Fixed
@HafizAnas kindly review

**Comment by HafizAnas** [comment]
Issue has been fixed and second point for feature/improvement, so added into feature.
