### ISSUE TITLE
Add Product Type On POS

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#171]
On POS we should add product type to improve check in workflow.

Admin can add new product type or disable/edit existing type _**i.e. mobile, tablet, etc**_

If someone doesn't want to keep workflow simple he can disable it via trigger.

![pos-category-images](https://cloud.githubusercontent.com/assets/21986026/21273668/6e2493b0-c3e6-11e6-816f-787713e4276c.jpg)

**Comment by Uzair-RepairDesk** [comment]
@Fazal-RepairDesk is working on functionality specification document of this task @aishahanif @itskamran

**Comment by Uzair-RepairDesk** [comment]
We have already developed this functionality a while ago. Details are available here:-
https://repairdesk.uservoice.com/knowledgebase/articles/1166230-how-to-enable-repair-categories-on-pos
