### ISSUE TITLE
Ticket shows as Completed but not all the jobs are done

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#174]
Hi Team, please see the attached photos for the issue. 

There is one job is waiting for part but the Ticket is showing as Completed, so we will not know if this ticket is overdue by looking at its status. Please look into this.

![issue with ticket](https://cloud.githubusercontent.com/assets/22993605/21299094/673a1ec8-c5ec-11e6-9b5e-5e02a9cb0afe.jpg)

**Comment by Repair-Desk** [comment]
**@quangc** can you email us your login details at support@repairdesk.co

**Comment by HafizAnas** [comment]
@quangc 

Your reported issue has been fixed. Kindly verify at your end and do let us know if you have any question.

Thanks
