### ISSUE TITLE
Issue With French Language

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#176]
**Dear @itskamran** 

One of our customer who translated the software in French is unable to create repair ticket because of special characters in it.

![sos phone pos](https://cloud.githubusercontent.com/assets/21986026/21435915/f41d8d62-c89d-11e6-8546-9845564f81e9.png)

You can check login details from intercom.

Please ask aisha or imran to fix it ASAP.

**Comment by hafeezshahid** [comment]
Customer Update through e-mail.
