### ISSUE TITLE
Select Serial Option - Create Ticket

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#177]
If you have created repair bundle it doesnt display select serial option on create ticket screen. Please have the developer add this option

![captura de pantalla 2016-12-29 a las 10 56 09](https://cloud.githubusercontent.com/assets/21986026/21541410/d4637308-cdd7-11e6-8f6b-9931f0ca17fd.png)

**Comment by HafizAnas** [comment]
Hi @Repair-Desk 
your requested change has been added so kindly verify at your end.
