### ISSUE TITLE
Repair Tracker - Multi Store Location

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#178]
If a customer has multiple store location there should be an option on backend that also allows you to generate iFrame code which than automatically display all locations on his website

![multi location](https://cloud.githubusercontent.com/assets/21986026/21541771/e6ac87d6-cdda-11e6-86b2-a0d5a72a68ec.png)

**Comment by HafizAnas** [comment]
Hi @Repair-Desk 
Your requested changes has been completed. Kindly verify at your end.
