### ISSUE TITLE
GST issue while adding part in multiple locations

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#18]
"when we add any new part or accessories in our Sefton Park store everything gets added in our Anzac store except GST. GST of the Anzac store doesn’t get checked even though we check tax inclusive box in Sefton store while adding a new part. And same is the case with repair inventory and as the GST does not get included it creates problem in our Anzac store. Please find attached screen shots for your reference."
![zarna_both stores gst - mobile-accessories-parts](https://cloud.githubusercontent.com/assets/22954033/19555053/a9d0012c-96d4-11e6-8cfd-b37ee21017d5.jpg)
![zarna_both stores gst - repairs](https://cloud.githubusercontent.com/assets/22954033/19555055/a9e4bbbc-96d4-11e6-810f-f77451229c05.jpg)

**Comment by hafeezshahid** [comment]
Issue not fixed @HafizAnas
