### ISSUE TITLE
Print Docket Option On End Shift

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#180]
There should be an option to **print reconciliation report** on mini receipt that will which will also open cash register and assist employees with the counting

Sample:

No Sale

Schaumburg

Do, Peter

30 - December 12:31 PM

Cash on Hand: $100.00
Net Receipts: $0.00
![image](https://cloud.githubusercontent.com/assets/24845573/21570382/2521093c-ce8b-11e6-9f45-818ad9f83cc5.png)

**Comment by smarttechrepair** [comment]
I've enabled bluefin but it doesn't display on end shift pop up window

**Comment by Repair-Desk** [comment]
Hi @smarttechrepair 

We have started working on this issue and hopefully it will be released during next week.

**Comment by muhammadfayyaz3** [comment]
Hi @smarttechrepair
kindly explain Net **Receipts: $0.00**.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair 
Your reported issue has been fixed and it working fine at our end. Kindly verify at your end and do let us know if you have any query.
