### ISSUE TITLE
Invoice terms and conditions don't change

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#181]
Just found this issue yesterday. We are trying to change the default terms and conditions for Invoice (not Receipt), and the changes are not applied. I think there is a bug, please review below screenshots.

<img width="955" alt="screen shot 2016-12-31 at 12 49 55 pm" src="https://cloud.githubusercontent.com/assets/22993605/21575167/4a613492-cf58-11e6-848d-6c9aac425843.png">
<img width="814" alt="screen shot 2016-12-31 at 12 52 04 pm" src="https://cloud.githubusercontent.com/assets/22993605/21575168/4a616228-cf58-11e6-85cd-7a98d7c568e2.png">

**Comment by quangc** [comment]
Apparently, it only appear on the invoices created after the time you change the terms, the previous invoices stays the same.

**Comment by HafizAnas** [comment]
Dear @quangc 

I hope you are doing well. It's working fine at my end now so kindly verify at your end and do let us know if you have any question.

Thanks for patience.
