### ISSUE TITLE
Customer driving license tag on invoice template editor

### ISSUE THREAD

**Issue by luisvae** [Repair-DeskPOS/RepairDesk-Bugs#183]
For legally working and issuing invoices in Spain, the customers ID number (customer driving license in Repair desk) must appear on the invoice. Otherwise it is illegal to issue invoices.
Please provide the tag customer driving license at the template editor.

**Comment by Repair-Desk** [comment]
****Dear @itskamran**** 

Can you ask a developer to add a trigger that allows you to add customer driving license. If possible try to get this shipped in next bug release (10th Jan, 2017)

![add customer - repairdesk](https://cloud.githubusercontent.com/assets/21986026/21588810/1f7fdc14-d10c-11e6-9656-03f6c389a910.png)

**Comment by itskamran** [comment]
Dear @Repair-Desk,

Assigned to developer. Soon we will have updates. Thanks

**Comment by HafizAnas** [comment]
Hi @luisvae 
Your requested changes has been added in invoice template editor. So kindly verify at your end and do let us know if you have any question.
