### ISSUE TITLE
Payroll reports

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#185]
Should have a "view all" stores function when selecting the store locations during payroll reports.  Being able to view all store location's employees payroll times would be more convenient.

**Comment by quangc** [comment]
There is option for this one already. Not sure if it's just been added but I've been using it for a while now.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair 

Your reported issue has been fixed. Kindly verify at your end and do let us know if you have any question.
