### ISSUE TITLE
Closing Cash Count Drawer Report Print

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#186]
When ending the store pos for the day, there should be a button so a summary report is printed through the receipt printer so the cash drawer can be opened and the currency counted and entered into the cash reconciliation screen.

**Comment by Repair-Desk** [comment]
@smarttechrepair thanks alot for your feedback.

We will be releasing option to print out summary report before end of this week.

**Comment by itskamran** [comment]
Dear All, It is fixed in new release. Ticket will be close now. Thanks
