### ISSUE TITLE
Multiple Device Upload Via CSV (Accessories Section)

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#187]
Under accessories tab if you import csv that has multiple device i.e. **iPhone 6, iPhone 6s, iPhone 7, iPhone 7** plus it creates one item with multiple devices. which is wrong.

![multiple device](https://cloud.githubusercontent.com/assets/21986026/21758684/e653d054-d65f-11e6-8c89-0519c75f0b91.jpg)

![multiple device1](https://cloud.githubusercontent.com/assets/21986026/21758709/14067182-d660-11e6-90d3-7f806d468236.jpg)

**Comment by RepairDeskPOS** [comment]
While importing a CSV file now you can use " | " to seperate devices.
