### ISSUE TITLE
Invoices showing Overpaid when it is not

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#19]
The system show that some customer overpaid sign whenin reality but the customer never did overpay
Inside the invoice it won't show overpaid and At the bottom it only show one payment but on manage invoices show overpaid

Hafiz Anas please review it. I guess Imran Qadir has already fixed it. 

Sir Imran: "issue has been fixed. issue was only if you search for accessories and if a invoice has multiple item then it duplicate the amount paid. Aisha Hanif  can you upload the revision # 557 from branch 5 please ." 

Mam Aisha: "Dear Anas,

please review the fix on both stores (staging and live ).

regards,
Aisha"
![adnan_1](https://cloud.githubusercontent.com/assets/22954033/19555181/3266851a-96d5-11e6-8071-e011f7ce2dc3.png)
![adnan_2](https://cloud.githubusercontent.com/assets/22954033/19555182/32905c32-96d5-11e6-9eaa-37eb1cc78f1e.png)
![adnan_3](https://cloud.githubusercontent.com/assets/22954033/19555183/32983506-96d5-11e6-8413-54a3440a1613.png)
![adnan_4](https://cloud.githubusercontent.com/assets/22954033/19555184/32afb640-96d5-11e6-835e-f73cac69fd79.png)
![adnan_5](https://cloud.githubusercontent.com/assets/22954033/19555185/32bf8de0-96d5-11e6-8d8e-17ebfbee7218.png)

**Comment by HafizAnas** [comment]
Issue has been fixed and it's working at my end.
