### ISSUE TITLE
Print Node 

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#190]
There should be a print node receipt button under the POS.  Currently cannot print using print node under POS.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair 

I have verified your reported issue at my end it's working fine at my end. Kindly verify at your end again and one more thing look into setting page once before verify. Do let us know if you have further any question. (See Attached Screenshots for detail)

![modsindex printnode](https://cloud.githubusercontent.com/assets/22954115/21840070/33e82a24-d7fd-11e6-8788-81aa7f4714c4.png)


![modsindex update printnode](https://cloud.githubusercontent.com/assets/22954115/21840071/33e95188-d7fd-11e6-9da6-6f18731877f7.png)
