### ISSUE TITLE
Show repair status when you re-open repair ticket

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#191]
When you are checking in customer or re-open an existing repair ticket it would be great if we can display repair status. See attached screenshot

![point of sale - repairdesk changes](https://cloud.githubusercontent.com/assets/21986026/21846471/1f10bc94-d819-11e6-8e07-6207acc1d43d.png)

**Comment by HafizAnas** [comment]
Hi @Repair-Desk 

Your requested feature has been added on POS. 
Kindly verify at your end and do let us know if you have any question.

**Comment by Repair-Desk** [comment]
**Please display a colored label so its more visible.**

![repairdesk pos](https://cloud.githubusercontent.com/assets/21986026/22339213/06128a8a-e40b-11e6-8db3-90ad1f631ce2.png)
