### ISSUE TITLE
Display inventory items in different color codes on invoice

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#193]
Just like inventory search we have on Point of sale screen, we should display inventory items in different color codes & also display heading like its an accessory or a casual item etc

![image](https://cloud.githubusercontent.com/assets/21986026/21878546/d553445e-d8b4-11e6-8852-ac4534a87fe6.png)

Reference:
![image](https://cloud.githubusercontent.com/assets/21986026/21878615/3fc99824-d8b5-11e6-93e0-5dd842191d06.png)

**Comment by Fazal-RepairDesk** [comment]
@Repair-Desk 
![github_193](https://cloud.githubusercontent.com/assets/22954033/23205379/78c521ea-f90b-11e6-9a7f-2bfa7c90610c.png)
The said issue has been fixed. Please see the attached screenshot for clarification.
