### ISSUE TITLE
Self check in module

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#195]
**Issue:**
it allow customer to submit without adding signature. Please test and fix.

**Enhancements:-**
Also customer phone number should be a mandatory field.

Also terms and condition checkbox should display under signature

**Comment by Repair-Desk** [comment]
There should also be an option that allows you to hide Manufacturer, device and network using a trigger. There are few customers who doesn't want to display this option

**Comment by HafizAnas** [comment]
Hi @RepairDeskPOS 
Your reported issue has been fixed. Kindly verify at your end.
