### ISSUE TITLE
Refund invoice should be linked to invoice

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#197]
I found it a bit hard to audit refund invoices since there is no records. Can we have a refund invoice shows in the original invoice so we can quickly go to the refund invoice and audit?

I think we should have a link like PO links to GRN.

If there is already a way then please tell me. Thanks.

**Comment by Uzair-RepairDesk** [comment]
Hi @quangc 
Currently you can filter the refund invoices from "Refund" status on Manage Invoices page. Once you refund the invoice and go to the "View" page of original invoice the internal status is also change to "Refund". There is also a reference of original invoice on refund invoice. Once you check the refund invoice and find out the customer name, you can also search original invoice from customer keyword. 

We have also planned to update refunds functionality in RepairDesk, It will allow you to not only give refunds with respect to specific quantity but also issue partial refund to the customers. We have completed functionality specifications document phase and its added in our road map. Thanks

**Comment by HafizAnas** [comment]
Hi @quangc 

Hope you are well. Your requested suggestion related to Refund Link on invoice like PO has been added. You can view link very next to Payment Invoice # ,

I would highly appreciate if you can confirm if it's working on your end . 

![invoice4](https://cloud.githubusercontent.com/assets/22954115/24452717/fc7b1726-149d-11e7-8934-791a03bb724e.png)


Please feel free to reach out if you have further question.

Thanks,
Hafiz Anas
