### ISSUE TITLE
Totals in Reports Not Shown Properly

### ISSUE THREAD

**Issue by luisvae** [Repair-DeskPOS/RepairDesk-Bugs#200]
The totals in the reports do not match properly. Some payments do not reflect on the totals. Others instead of adding value, they subtract and viceversa. We have seen it in various cases. Please look at this example where the payment is reflected below as "bank transfer" but it shows the amount to be due. If we removed the payment from the invoice, the due amount disapears. Logically the inverse of what it should do:
![captura de pantalla 2017-01-19 a las 14 26 41](https://cloud.githubusercontent.com/assets/18724945/22108412/538acc90-de53-11e6-8fc0-f1320bf816d8.png)

We have seen other totals around the reports that do not sum correctly.

**Comment by HafizAnas** [comment]
Hi @luisvae 
We have tried many times but we are not able to reproduce this issue. Kindly check at your end again and share steps with us.

**Comment by itskamran** [comment]
Hi @luisvae, If you face this issue again, please feel free to reopen this ticket. Thanks
