### ISSUE TITLE
Error message when closing shift print reconcilation report

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#204]
{"token":"1485825430588fe5962dc8e","status":1}

Message received when trying to print reconciliation report when ending shift.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair

I apologize for inconvenience,
your reported issue has been assigned to developer and it will be fixed soon.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair 

Your reported issue has been fixed. Kindly verify at your end and do let us know if you have any question.
