### ISSUE TITLE
SUGGESTION - Inventory Count per Inventory type

### ISSUE THREAD

**Issue by luisvae** [Repair-DeskPOS/RepairDesk-Bugs#209]
It would be great to be able to choose which kind of product are we going to count on inventory count. Now, if we miss counting 1 product, it will not be reflected as missing. 

By choosing inventory type (eg spare parts, mobile phones, accessories) if we miss 1 product counting, it will be reflected as missing, without having to count the whole inventory.

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk Do you think we can add the ability to choose item type for inventory count?

**Comment by Uzair-RepairDesk** [comment]
Hi @luisvae 
Thanks for your suggestion. I think that’s an awesome idea! Having it would definitely provide the ease during inventory count. Admin/users will be able to select item type e.g. "Accessories" and only accessories items will come up in the list to count. 

We’re not working on that at the moment but I’ll pitch it to the team and see what they think.

If you have any other questions, just let me know and I’ll be happy to help.

Regards,
Uzair

**Comment by Uzair-RepairDesk** [comment]
We have already updated our Inventory Count module that allows you to select a particular category (type) to count the items. 
Please find details in following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1119253-how-does-the-inventory-count-functionality-work
