### ISSUE TITLE
Multiple location log in

### ISSUE THREAD

**Issue by jelder09** [Repair-DeskPOS/RepairDesk-Bugs#210]
Companies with multiple locations when logging in, a box should pop up prompting you to select your location.  My employees move store to store and occasionally run sales or open the register for a different location because they did not notice what store the system logged them into.

**Comment by Fazal-RepairDesk** [comment]
Hi @jelder09. In Employee Settings we have an option to choose default store and access for employee for a particular store. Admin can choose default store for employee, and system will automatically log him in that default store.
To set default store for an employee, please go to **Settings >> Employees >> Manage Employees**. Click on **Action** button against an employee and select **Edit**.   
Under **Role & Access**, select default store for the employee and hit **Save** button. 
Now the employee will see this store whenever he logs in. 
To show all tickets to employees, regardless of their store locations, please go through this informative article: https://repairdesk.uservoice.com/knowledgebase/articles/922005-is-there-a-way-to-show-tickets-to-all-employees
If you still need any kind of assistance, please do let us know. Thanks.
