### ISSUE TITLE
Sales By Repairs Reports Error

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#211]
Sales by repairs report does not allow you to print.  Also the totals on multiple pages do not add.  If there are multiple pages in Sales By Repairs, the last page should have a total showing the sales for the entire day.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair 

Sorry for inconvenience, Your reported issue has been assigned to developer and it will be fixed soon.

**Comment by Fazal-RepairDesk** [comment]
Hi @smarttechrepair !
Regarding your issues here is the following feedback:
1. _Sales by repairs report does not allow you to print_ (**This issue has been resolved**)
2. _The totals on multiple pages do not add_ (**It cannot be added on multiple pages. Instead it would be added on a single page, which is working fine. You can use pagination feature and expand number of results per page.**) 
3. _If there are multiple pages in Sales By Repairs, the last page should have a total showing the sales for the entire day_ (**You can use filters to accommodate this one**).
