### ISSUE TITLE
Multiple Store Reports Error

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#213]
Cannot check reports for multiple stores without having to log into a particular location and then pulling the reports.  Should be able to pull daily reports from the multiple store reports, however reports only show for the particular location we are logged in.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair 

Currently, you can not view any specific report  without log into particular location but you can view main stats (facts and figures) of any particular location through Multi store reports.
