### ISSUE TITLE
Partial Refunds !!!

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#214]
Must be able to issue partial refunds for single or multiple line items.  For example with the customer purchased an iPhone 6 screen replacement for $100 cash or credit.  We should be able to give a partial refund for any amount in either cash or credit depending on the initial payment method used.  At the least we must be able to give a partial refund in cash when customer initially paid with credit card.  This is a HIGH PRIORITY issue.  MUST BE ABLE TO DO THIS in the REAL world!!!

**Comment by HafizAnas** [comment]
Hi @smarttechrepair,
Sorry for Inconvenience, We are already working on it and It will be live soon.

**Comment by Uzair-RepairDesk** [comment]
Hi @smarttechrepair 

I hope you are doing good. This is to to inform you that we have completed Functionality specification document for partial refunds and development of this functionality is part of our roadmap. 

Regarding Payment method for refunds, you can certainly use different payment method for refunds right now. E.g. if you have taken the payment of invoice from credit card and you go for refund, you can choose different payment method like cash on checkout. 
I hope it helps.

Please do let me know if you are facing any issue in above scenario and I 'll be happy to assist you. Thanks.

**Comment by Uzair-RepairDesk** [comment]
Hi @smarttechrepair 
We have added partial refunds functionality in RepairDesk a couple of months ago. You can find details from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/895113-how-can-i-process-refund-exchange-in-repairdesk

**Comment by quangc** [comment]
Has it been allowed for partial refunds?

**Comment by quangc** [comment]
![screen shot 2018-07-23 at 12 02 31 pm](https://user-images.githubusercontent.com/22993605/43053536-94282f44-8e70-11e8-9497-712c255321b0.png)
As it can be seen here that the item is $160, and customer paid only $60, now I want to do refund and the system does not allow me.

**Comment by Uzair-RepairDesk** [comment]
Hey @quangc, We have partial refund functionality available with respect to quantity and amount but its available only for "Paid" invoices. Partially paid invoices depict that sales value is not fully received so refund option doesn't come up in the above scenario. To find more information about existing partial refund functionality, you can check the articles below:-
https://repairdesk.uservoice.com/.../895113-how-can-i...

In case of above scenario, you can either log the remaining amount first and then refund the full invoice, or you can open an existing invoice and add a new line item with negative quantity so $60 will become negative to make the invoice value $0.

**Comment by quangc** [comment]
Why we dont allow refund on those not fully paid invoices? What is the difficulty?

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.
