### ISSUE TITLE
Invoice Amount Issue

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#22]
Customer is facing an issue regarding invoice.
For example, if repair cost is $100, basic is $90.91 and GST is $9.09.
In the ticket page, there is no problem before making invoice.
But, when the payment is made, invoice shows wrong amount.
In the invoice, total is $90.91. basic is $82.65 and GST is $8.26.
So, he currently edits it manually. 
He can't issue invoice when my customer makes payment
He is following below steps:
1. Entered info and created ticket in POS. (Photo 1)
In the photo, 6G screen replacement is $140 (inc GST $12.73) and protector $10 (inc $0.91), total $150.
2. After repairs, the customer made payment. (photo)
You can see wrong price.
6G was $127.2 and GST $12.7. But, it is $115.7 and GST $11.57.
This page must show $140 ($127.2 and $12.7), but it shows $127.2 (115.7 and 11.57)
During the payment process, GST is calculated twice. $140 -> $127.27 and $12.7 -> $115.7 and $11.57
This is report page. It shows wrong price. Total sales price is $127.27 (not $140)
Due to this issue, he can’t provide invoice for his customer. If his customer requires tax invoice, he needs to edit manually and it takes longer time.
![kwon_issue1_1](https://cloud.githubusercontent.com/assets/22954033/19556800/494cd872-96dc-11e6-894f-3b3a94ab0c37.png)
![kwon_issue1_2](https://cloud.githubusercontent.com/assets/22954033/19556801/494cf4ec-96dc-11e6-96b7-1be0601de38c.png)
![kwon_issue1_3](https://cloud.githubusercontent.com/assets/22954033/19556804/49535dfa-96dc-11e6-810c-27f6acd21e03.png)
![kwon_issue1_4](https://cloud.githubusercontent.com/assets/22954033/19556802/494fce56-96dc-11e6-9cac-f692dd4eb894.png)
![kwon_issue1_5](https://cloud.githubusercontent.com/assets/22954033/19556803/4951231e-96dc-11e6-8b54-d259073977de.png)
![kwon_issue1_6](https://cloud.githubusercontent.com/assets/22954033/19556805/497ce81e-96dc-11e6-872c-b51cea3a716c.png)

**Comment by HafizAnas** [comment]
Issue Fixed and It's working fine at my end.
