### ISSUE TITLE
Calendar book in widget not saving customer address

### ISSUE THREAD

**Issue by josephifixhq** [Repair-DeskPOS/RepairDesk-Bugs#220]
When a customer books in using the calendar book In widget the address is not saved to the new lead. Makes it especially difficult when 100% of our repairs are pick up or on site, and we don't have an address stored.

**Comment by Repair-Desk** [comment]
@josephifixhq We sincerely apologize for inconvenience & hopefully it will be fixed before end of this week.

**Comment by Repair-Desk** [comment]
@itskamran I've already assigned it to you on asana.

**Comment by RepairDeskPOS** [comment]
@josephifixhq reported issue with address has been fixed. Please verify it on your end
