### ISSUE TITLE
SMS canned response not being sent when a lead is converted to a ticket

### ISSUE THREAD

**Issue by josephifixhq** [Repair-DeskPOS/RepairDesk-Bugs#221]
I have selected *send customer SMS when a new ticket is created. However when I convert a lead to a ticket the SMS is not being sent.

**Comment by Repair-Desk** [comment]
@itskamran can you check this please

**Comment by itskamran** [comment]
@Repair-Desk Assigned to developer, soon we will have updates. Thanks

**Comment by Repair-Desk** [comment]
@itskamran What's the update on this one?

**Comment by itskamran** [comment]
@Repair-Desk, It is on demo server now, soon it will be finished. Thanks

**Comment by HafizAnas** [comment]
Hi @josephifixhq 

I hope you are doing well. Your reported issue has been fixed, Kindly verify at your end and do let us know if you have any question.

Thanks!
