### ISSUE TITLE
Create Ticket Button in POS

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-Bugs#222]
I do not like the create ticket button since my sales is not accurately being accounted.  I only would like use the checkout button.  Please allow for a feature that will turn off the create ticket button in Point of Sale.  If technicians accidentally press create ticket it would throw off our sales figures. Thanks.

**Comment by Repair-Desk** [comment]
@smarttechrepair If an employee creates a ticket by mistake you can quickly convert it to an invoice. More information is available here: https://repairdesk.uservoice.com/knowledgebase/articles/921069-how-to-create-invoice-for-an-existing-repair-ticke
