### ISSUE TITLE
Repair booking widget not creating lead emails

### ISSUE THREAD

**Issue by andrewg1639** [Repair-DeskPOS/RepairDesk-Bugs#223]
Our repair booking widget has been working perfectly, however today I have edited a setting in.
Settings>Integration>Appointment calendar widget>Alerts
I have ticket display alerts to two of our users.
However I noticed as soon as this has been done the display comes up to the user as it should, however no email is generated anymore.
I have tried to un tick the users however it will not allow me to save it with no users ticked.
I believe this is where the issue has been caused.
I would prefer to only get lead emails if it is a choice of either emails or alerts.

**Comment by andrewg1639** [comment]
Emails were temporarily coming through last night again, however today we had two more leads created, we got the notifications however no email was sent, have we got a setting wrong or is it a bug?

**Comment by Repair-Desk** [comment]
**Hi @andrewg1639** 

We apologize for inconvenience. Our QA team will review and revert back to you.

@itskamran Can you please have someone test this issue.

**Comment by itskamran** [comment]
@Repair-Desk: Assigned to QA, soon we will have updates. Thanks

**Comment by Fazal-RepairDesk** [comment]
@andrewg1639 Hi Andrew! Our team had a look at this issue and it's working fine. Please check your Spam Folder, perhaps the mail got in there. Also my development team has recommended that you should test by changing your store email addresses.

**Comment by andrewg1639** [comment]
Thanks Fazal

Yes they seem to be working fine again now, it must have been a bug that’s disappeared.

 

     Kind Regards

     Andrew Gardiner



Brisbane Airport DFO : 07 3114 1177 – Shop 206 DFO Shopping centre, Ninth Ave, Brisbane Airport

 

Jindalee DFO : 07 3114 1177 – Shop 73 DFO Shopping centre, 16 Amazons place, Jindalee

 

 

***Disclaimer

This email and any attachments transmitted with it may contain information that is confidential, legally privileged or both and is intended solely for the use of the individual(s) or entity to whom it is addressed. No confidentiality or privilege is waived or lost by any mis-transmission. If you are not a named addressee, you should not disseminate, distribute or copy this email or its attachments. Please notify the sender immediately by email if you have received this email by mistake and delete this email and its attachments from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the information contained within this email is strictly prohibited. Any views expressed in this email are those of the individual sender except where the sender expressly, and with authority, states them to be the views of Pimp my Gadget. Warning: Although Pimp my Gadget has taken reasonable precautions to ensure no viruses are present in this email or its attachments, the company cannot and does not accept responsibility for any loss or damage arising from the use of this email or its attachments.
