### ISSUE TITLE
ISSUE Exporting CSV delimited by commas 

### ISSUE THREAD

**Issue by luisvae** [Repair-DeskPOS/RepairDesk-Bugs#224]
When exporting files on CSV delimited by commas and there are text fields with commas this destroys the possibility of separating the fields as each comma on text generates a new field / column.

**It would be great to use semicolon ; to separate fields or use " " between text fields.** 

This happens in invoice exporting and customer exporting.

**Comment by itskamran** [comment]
Hi @luisvae, Thanks for reporting this issue, I have assigned it to the developer to look in to it on priority basis. I will update you very soon. Thanks

**Comment by Repair-Desk** [comment]
@luisvae We have added requested enhancement to RepairDesk platform. Please verify the changes on your end.

**Comment by Fazal-RepairDesk** [comment]
Hi@lui

**Comment by Fazal-RepairDesk** [comment]
Hi @luisvae! 
We've added the said functionality and it's working fine. Therefore we're closing this. 
In case you face any issue in it, please feel free to open this issue again and do let us know. 
For further assistance you may contact our support team as well. 

Team RepairDesk
