### ISSUE TITLE
Multiple Error 404  in different sections

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#23]
Customer: Luis
Business: Movilsat

Issues:
1. Google calendar integration replies with 404 error. 
2. Also SMS notification (Error 404)
3. {STORE_NAME} 
We have received it with the FIELD NAME instead of actual name. Only telephone number appeared correctly. In the email we have no problem. 
4. "Also we cannot create employees. We save them but they do not appear. 
We see customers are shared between our 2 stores. Is there a possibility not to share them? 
This is the screenshot of Google Calendar integration" (see below)

Email today:
"Hi Luis,

I checked with the development team. We’re working on the Google Calendar Integration issue you’re facing. As for the rest of the issues here are the comments on them:
1. Errors on SMS notifications – Working 100% (Please clear your browser cache and try again)
2. Creating Employees – Working 100%  (Please clear your browser cache and try again)
3. Customers shared between our 2 stores. Is there a possibility not to share them – It’s the default behaviour of RepairDesk

Please elaborate the following issue:
“{STORE_NAME} --- (cannot understand where such issue occurs. please identify page and steps) We have received it with the FIELD NAME instead of actual name. Only telephone number appeared correctly. In the email we have no problem.”

I’m also adding Aisha from the development team in this thread. If you need any kind of assistance or help, don’t hesitate to ping me  

Regards,

Fazal Ur Rehman"

**Comment by aishahanif** [comment]
@Fazal-RepairDesk  please provide us customer reply on this  so we can complete this task

**Comment by Fazal-RepairDesk** [comment]
I'm redirecting the customer here so that he can reply to your comments
