### ISSUE TITLE
ISSUE - Tax not calculated properly on purchase order section

### ISSUE THREAD

**Issue by luisvae** [Repair-DeskPOS/RepairDesk-Bugs#232]
The tax is not calculated properly on purchase order. We need to change tax type several times to get final good result. 

We enclose a video. 

[20170314_172334.mp4.zip](https://github.com/Repair-DeskPOS/RepairDesk-Bugs/files/842011/20170314_172334.mp4.zip)

**Comment by HafizAnas** [comment]
Hi @Luisvae
I apologise for inconvenience, Let me check and revert back to you soon.

**Comment by HafizAnas** [comment]
Hi @luisvae 
Your reported issue has been assigned to developer and it will be fixed soon.

**Comment by HafizAnas** [comment]
Hi @luisvae 
Your reported issue has been fixed. Kindly verify at your end and do let us know if you have any question.
Thanks!
