### ISSUE TITLE
View invoices and tickets from Point of Sales - Limit to open items

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-Bugs#236]
When checking out a customer inside the POS module we hit view invoices and all invoices show including ones that have been paid, when checking out a customer this should default to only show open invoices (same with view by ticket) you could still have a button for view all but unless we are doing a return we only need to see the open items and if they are picking up a few days later its hard to find the customer again without searching by name or ticket number

**Comment by Fazal-RepairDesk** [comment]
Hi @wirelessrepairzone 
This functionality has been added.
