### ISSUE TITLE
checkout in POS with 0 dollar sale

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-Bugs#237]
when checking out a customer we cannot close the sale/workorder inside POS if there is no charge. We do not charge to do a diag on a device, so when a customer comes in we ring up a new sale as a diag with no charge, it lets us hit checkout and they sign that they are dropping off the equipment. If we complete an actual repair we update the ticket with the approved repair and dont have any issues but if they dont want it fixed or it cant be fixed we have to close the workorder from the workorder area, if you pull it back up in POS checkout if grayed out. By not having checkout available we car not having the customer sign at pickup and have to exit the POS module and close the ticket from another screen

**Comment by Fazal-RepairDesk** [comment]
Hi @wirelessrepairzone 
Thanks fro your feedback. I've forwarded request to our team and will keep you posted about latest developments. 

Regards,
Fazal
RepairDesk
