### ISSUE TITLE
estimate receipt 

### ISSUE THREAD

**Issue by mpmdover** [Repair-DeskPOS/RepairDesk-Bugs#247]
will not show security code on estimate thermal receipt and unable to change the default receipt title for the estimate thermal printout

**Comment by Fazal-RepairDesk** [comment]
Hi @mpmdover 

I've noted down you issue and forwarded it to our team. Once I get a feedback. I'll update you.
Thanks for your patience.

Regards,
Fazal

**Comment by Fazal-RepairDesk** [comment]
Hi @mpmdover 
We're able to change the title of the estimate thermal receipt using Integrations>Template Editor> Estimate Thermal Receipt Template> Edit
We're checking the security code issue as well.

**Comment by mpmdover** [comment]
thanks

**Comment by usmanalikhan93** [comment]
Hello @mpmdover!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
