### ISSUE TITLE
Invoices API

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [Repair-DeskPOS/RepairDesk-Bugs#253]
The Invoice API URL isn't working. 
https://api.repairdesk.co/api/web/v1/invoices?api_key=xxxxxxxxxxxxxxxx
returns 
`{
  "success": false,
  "statusCode": 100,
  "message": "No Result Found",
  "data": []
}`

all other endpoints return valid data.

**Comment by Uzair-RepairDesk** [comment]
Hi Jonathan, 
**I got the following update from our development team:-**
"You are missing parameter. We also highlighted the following text in our [Knowledge base](https://repairdesk.uservoice.com/knowledgebase/articles/1189105-public-api) article:- "

"By default, it returns today invoices if no parameter is passed for the search. If you want to get yesterday, 7 days 30 days invoices pass a parameter named “filter” 1 for yesterday 7 or 30 etc. if you want to get all invoices send 0 in this parameter."

Please try the following URL and it will return all the invoices:-
https://api.repairdesk.co/api/web/v1/invoices?api_key=mUz8SpB-hyAO-HMxe-NQC9-Gy5oqQ1IR&filter=0

I hope it helps.

Regards,
Uzair
