### ISSUE TITLE
Unable to Add a new Employee [Urgent]

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#26]
Many customers are reporting that they are unable to add a new employee in RepairDesk. I've tried it myself on one of the accounts. When the employee details are entered and saved the screen shows that it is refreshing and it goes back to the page where details about the new employee can be added. When you go back to the Manage Employees section the newly added employee is still not visible, even if you tried to save it. 

Mam Aisha, Please assign it to Fayyaz with the tag of Urgent.

**Comment by Fazal-RepairDesk** [comment]
@muhammadfayyaz3 Also please change the label in from of the default store from select role to select default store. Please see the attached screenshot below
![add employee  @issue](https://cloud.githubusercontent.com/assets/22954033/19588487/7f204544-977f-11e6-8c1d-6c94bfafeaef.png)

**Comment by Fazal-RepairDesk** [comment]
@muhammadfayyaz3 As discussed this error is also showing even if the store is selected
![add employee issue_2](https://cloud.githubusercontent.com/assets/22954033/19588906/450e677a-9782-11e6-8bdb-b60047d5a399.png)

**Comment by muhammadfayyaz3** [comment]
Issue Fixed
@HafizAnas kindly have look

**Comment by Fazal-RepairDesk** [comment]
@HafizAnas any update?

**Comment by muhammadfayyaz3** [comment]
@Fazal-RepairDesk Issue fixed kindly review at your end.

**Comment by hafeezshahid** [comment]
Issue Fixed and reviewed.
