### ISSUE TITLE
Duplicate customer names in drop-down search box

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#27]
Please fix duplicate customers shown in customer drop-down search box.
![customer drop box](https://cloud.githubusercontent.com/assets/22953208/19589126/c657b734-97ad-11e6-8125-d75c4cd29f6a.jpg)
![customer drop box-2](https://cloud.githubusercontent.com/assets/22953208/19589127/c66628b4-97ad-11e6-8495-0a0a97eafdf0.jpg)

**Comment by aishahanif** [comment]
@hafeezshahid @HafizAnas  fix is on staging please review

**Comment by hafeezshahid** [comment]
Reviewed on staging, issue fixed.
@aishahanif please make it live.

**Comment by HafizAnas** [comment]
@TechnologyTraders 
Your Reported issue has been fixed and it's working fine at my end.
Please do let me know if you still have any problem against this issue.
