### ISSUE TITLE
Inventory Count Error

### ISSUE THREAD

**Issue by kristan79** [Repair-DeskPOS/RepairDesk-Bugs#278]
Everytime  We are counting skus a different category pulls up
![screenshot 2018-02-14 13 51 53](https://user-images.githubusercontent.com/33140884/36224812-4a640612-118e-11e8-9077-ed7462f57dd1.png)

**Comment by Repair-Desk** [comment]
@kristan79 

Sure thing! Let us take a look to see if we are getting the same issue as you and we'll circle back to you.
