### ISSUE TITLE
Cannot Cancel in POS when no item is entered

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#28]
If the default customer is updated then we should be able to cancel the invoice..
![cannot cancel with customer name](https://cloud.githubusercontent.com/assets/22953208/19589257/87b7adc6-97ae-11e6-9499-663280664a1b.jpg)

**Comment by Uzair-RepairDesk** [comment]
@TechnologyTraders 
If you select/update customer and want to switch the customer to default, you can again select "Walk In Customer" or other customer. 
Cancel button works if you add any item in the order and want reset the screen.

**Comment by TechnologyTraders** [comment]
Then please improve the speed to look up customers. I would have to waste up to 10sec wanting for the list to cache again just to change back to walkin customer..
