### ISSUE TITLE
Refunds are not refunding

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-Bugs#282]
Heyo,

Refunds are not going through. I've tried several different ways with test transactions and each time the money is taken out of our account but is never refunded.

**Comment by Repair-Desk** [comment]
Hello @TPRS 

We sincerely apologize for the inconvenience. Are you currently processing refunds through one of our payment integrations i.e. Cayan. Please confirm so we can assist you accordingly.
