### ISSUE TITLE
Warranty default is years?

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-Bugs#283]
At the customer intake, the warranty defaults to 'years'. Even though our default is 'days'
![image](https://user-images.githubusercontent.com/36774732/36646171-c9268610-1a39-11e8-8ef2-b007ae952fa7.png)

**Comment by Repair-Desk** [comment]
Sure thing! Let us take a look to see if we are getting the same issue as you and we'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @TPRS!
This issue has been fixed now. You may check. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
usman ali khan
