### ISSUE TITLE
Injured Gadgets Broken Link

### ISSUE THREAD

**Issue by 406cell** [Repair-DeskPOS/RepairDesk-Bugs#286]
![capture](https://user-images.githubusercontent.com/37097126/37015536-0fc8f850-20c5-11e8-87a2-9c809fbc1198.PNG)

bad link https://www.injureddadgets.com/

**Comment by HafizAnas** [comment]
Hi @406cell 
Reported issue has been fixed and kindly verify at your end and do let us know if you have any question.
