### ISSUE TITLE
Multi Same Serialized Inventory Number

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-Bugs#287]
![image](https://user-images.githubusercontent.com/36774732/37114682-9c89b276-220e-11e8-8a51-5feeb981fda9.png)

**Comment by Repair-Desk** [comment]
Sure thing! Let us take a look to see if we are getting the same issue as you and we'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hello @TPRS!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
