### ISSUE TITLE
Custom Status colours not changing

### ISSUE THREAD

**Issue by rsrikhan** [Repair-DeskPOS/RepairDesk-Bugs#290]
I tried to assign a custom status colour and it is not changing the colour. I used this hex code #4DBC85

**Comment by Repair-Desk** [comment]
@rsrikhan Can you please confirm if you are trying to edit default ticket status color?

Currently its not possible to edit default ticket status color!

**Comment by Uzair-RepairDesk** [comment]
I checked it, If we give custom HEX code to custom ticket status, it doesn't update it. 
I believe this is the issue @rsrikhan has reported above.

@usmanalikhan93 
Please discuss it with Sajjad sb if possible and report it on Jira.

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk 
It looks like there's a bug that just popped up 🐛. I'm gonna reach out to our Engineers to get this taken care of.

**Comment by usmanalikhan93** [comment]
Hey @rsrikhan!

It looks like this bug has been squashed! Can you refresh your browser and let me know if you're able to assign a custom status colour or not? 
usman ali
