### ISSUE TITLE
Tabbing new customer details on ticket

### ISSUE THREAD

**Issue by rsrikhan** [Repair-DeskPOS/RepairDesk-Bugs#291]
When hitting the 'tab' key during the 'adding a new customer' (via new ticket creation) results in the field going down the page rather than across. 

So instead of hitting tab and going from First name to last name it goes to down to email

**Comment by HafizAnas** [comment]
Hi @rsrikhan,
I apologise for the inconvenience, you can not add new customer from create ticket screen, tab key looks good when you click on create ticket page.
Kindly have a look attached screenshoots and I hope it will help you.
![31](https://user-images.githubusercontent.com/22954115/37892309-e0f41a46-30f0-11e8-81a1-a72548e4b568.png)
![32](https://user-images.githubusercontent.com/22954115/37892310-e1251326-30f0-11e8-8130-a549e9d004ec.png)

**Comment by Repair-Desk** [comment]
@HafizAnas When you click on customer group and press tab it shifts to ticket summary.

Also if you are on Mobile and press tab it doesn't move you to "device details"

**See below:**

![Uploading Device.png…]()

**Comment by usmanalikhan93** [comment]
Hi @rsrikhan,
This issue has been fixed now. You may check. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
