### ISSUE TITLE
Notes do not save on already submitted purchase orders

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-Bugs#292]
If I open a purchase order, add a note, and save... it does not save on the po. When you open again it is gone.

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw!
It looks like this bug has been squashed! Can you check and let me know if you're still facing this issue.

**Comment by phonefixdfw** [comment]
looks like it works now
