### ISSUE TITLE
Appointment calendar widget: First name , Last name  capacity one word only

### ISSUE THREAD

**Issue by youzlar** [Repair-DeskPOS/RepairDesk-Bugs#294]
in Appointment calendar widget  after saving theses information 
 
First Name :   Masood Ahmed
Last Name : Mohammad Jan

the remain names ignored 
![2018-04-02_14-14-46](https://user-images.githubusercontent.com/2124196/38194572-fa22dde6-3680-11e8-915c-01f241369114.png)
![2018-04-02_14-16-07](https://user-images.githubusercontent.com/2124196/38194575-02251004-3681-11e8-81b4-241cb7447d12.png)
![2018-04-02_14-17-11](https://user-images.githubusercontent.com/2124196/38194584-0b71148c-3681-11e8-84c7-70d260ddbe8a.png)
![2018-04-02_14-18-26](https://user-images.githubusercontent.com/2124196/38194589-140a1774-3681-11e8-82bb-67bbdc74af78.png)

**Comment by usmanalikhan93** [comment]
Hi @youzlar!
It looks like this bug has been squashed! Can you refresh your browser and let me know if you're still facing this issue.
