### ISSUE TITLE
POS Quantity Calculation Error

### ISSUE THREAD

**Issue by ellbristow** [Repair-DeskPOS/RepairDesk-Bugs#297]
I have a Casual item in my POS "Quick Fix" for €10.

If I tap it once, it adds a line with quantity 1 and price €10.
If I tap the same item again, it adds a second line with quantity 2, line total €20... meaning 3 have been added rather than 2.

EllTecnico

**Comment by Repair-Desk** [comment]
@ellbristow Thanks for bringing this to our attention and we will try to release a fix within 1 - 2 weeks time!

**Comment by usmanalikhan93** [comment]
Hey @ellbristow!
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by usmanalikhan93** [comment]
Hi @ellbristow!
It looks like this bug has been squashed! Can you refresh your browser and let me know if you're still facing this issue or not? 
usman ali
