### ISSUE TITLE
Exporting Customers Error 403

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#30]
It's been like this for a long time and last time I requested this to be fixed including duplicate customers in search box I have heard nothing..Please fix this so that we can easily filter through all those duplicates due to RD creating duplicates from editing customers a while back. This error occurs with limited account, but when I use my account with super user access I am greeted with a blank page.
![export customers blank page](https://cloud.githubusercontent.com/assets/22953208/19589644/daf0dd26-97b0-11e6-812f-df41a6123509.jpg)
![export customers error](https://cloud.githubusercontent.com/assets/22953208/19589645/daf6f59e-97b0-11e6-838b-aebe6ec240f2.jpg)
![export customers](https://cloud.githubusercontent.com/assets/22953208/19589646/daf71434-97b0-11e6-94a8-baf012df95a2.jpg)

**Comment by Repair-Desk** [comment]
@aishahanif If the customer size is more than 3000 it times out and gives error

**Comment by muhammadfayyaz3** [comment]
I am on it @aishahanif

**Comment by muhammadfayyaz3** [comment]
Issue has been fixed

**Comment by hafeezshahid** [comment]
Issue Fixed and reviewed on staging
@aishahanif please make it live.

**Comment by HafizAnas** [comment]
Hi @TechnologyTraders 
Your Reported issue has been fixed and it's working fine at my.
Please do let me know if you still have any problem against this issue.
