### ISSUE TITLE
Google Cloud / PrintNode - Option to disable automatic label printing on iPAD app

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#301]
There should be a trigger which you can turn on / off that should disable label printing on checkout as it should only print thermal receipt on payment checkout.

On desktop POS it works fine however on iPAD POS register after the last update its printing extra label which is inconvenient!

**Comment by imiamran** [comment]
Thanks for highlighting this issue. we are working on it and it will be fixed in next 24 hours.

**Comment by usmanalikhan93** [comment]
This issue has been fixed.
