### ISSUE TITLE
Duplicate Barcodes

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#306]
Hi just curious, is there anyway for the system not to use the same UPC or SKU twice? I added two products with the same barcode would be nice to get a warning etc of duplicate codes.

**Comment by Uzair-RepairDesk** [comment]
We have already trigger available to make uniqueness across SKU.
Trigger is under [Settings > Module Configurations > Inventory ](https://app.repairdesk.co/index.php?r=config/inventory)
