### ISSUE TITLE
Re-Open Repair Tickets in POS

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#31]
Why still have 2 methods when we are told not to use 'tickets' from the drop down? make everything unified..Just allow the search bar for inventory.
![remove this drop-down menu](https://cloud.githubusercontent.com/assets/22953208/19589809/cab27658-97b1-11e6-9948-cdca949f892c.jpg)

**Comment by imiamran** [comment]
By default setting is set to inventory search, its not a bug . if you don't need to use ticket and invoice search just don't click on this dropdown .

**Comment by Repair-Desk** [comment]
@imiamran can we get rid of it so by default it only search inventory items

**Comment by Fazal-RepairDesk** [comment]
@imiamran can you please update about it?

**Comment by aishahanif** [comment]
@Fazal-RepairDesk  we have  already updated you its no a bug. by default inventory option is selected. user can search ticket and invoices according to selected option.
