### ISSUE TITLE
Rounding Issues

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#32]
Still occurs a lot and not only when finalising payments. Should be $50.00...but instead there are 3 different figures. $50 due, balance of $49.99 and apparently CASH received is $49.995. This is a refund, but the same thing happens with sales. We also have values jumping around when in edit ticket which I don't have time to go in to.
![rounding issues](https://cloud.githubusercontent.com/assets/22953208/19589896/4c47371c-97b2-11e6-953a-9e8de63965eb.jpg)

**Comment by Uzair-RepairDesk** [comment]
@HafizAnas 
can you please review and get it fixed.

**Comment by Uzair-RepairDesk** [comment]
@TechnologyTraders 
Can you review and check if its fixed at your end. Please do let me know if the issue still persists

**Comment by HafizAnas** [comment]
![rounding issue](https://cloud.githubusercontent.com/assets/22954115/20213294/c8933898-a829-11e6-82a4-e3f882eeb5f2.png)

**Comment by HafizAnas** [comment]
![rounding issue1](https://cloud.githubusercontent.com/assets/22954115/20213652/87528292-a82b-11e6-9f0d-c67aa2097665.png)

**Comment by Fazal-RepairDesk** [comment]
@TechnologyTraders Hi There! We have not seen any issue on POS page after last change in pricing behavior for POS. 
Can you please verify this at your end as well?

**Comment by Fazal-RepairDesk** [comment]
Our team has tested all rounding issues faced by customers and now it is working smoothly. Customers have verified this on their end as well. Everything is being calculated now in a much refined and effective manner, without any error. Therefore, we are closing this issue. 
In case if you are still facing this issue, please don't hesitate to contact us! If you're facing this issue again at some future time, please re-open this issue and do let us know. 
Always here, to serve our valuable customers.

Team RepairDesk
