### ISSUE TITLE
Customer Portal - Print Label causes hang

### ISSUE THREAD

**Issue by geelongmicrosoldering** [Repair-DeskPOS/RepairDesk-Bugs#320]
When trying to print a label using the customer portal, nothing happens upon clicking the Print Label button.

Further attempts to click anything result in a browser stall, and the only way to recover is to refresh.

To reproduce, create a ticket via customer portal, then click print label

**Comment by Repair-Desk** [comment]
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @geelongmicrosoldering ! 
I have thoroughly checked your concern, I have created a ticket via customer portal and then click on print label, and it's working perfectly fine. If you still face issue, do let me know.

**Comment by geelongmicrosoldering** [comment]
Imran Qadir has confirmed the bug exists. I sent him a portal link and he replicated it.

Other users havr also

**Comment by imiamran** [comment]
@geelongmicrosoldering your reported issue has been fixed today. it was happening on those accounts who has customised their ticket labels.

**Comment by geelongmicrosoldering** [comment]
Confirmed it is now working. Thanks. Closing
