### ISSUE TITLE
Mandatory Email

### ISSUE THREAD

**Issue by geelongmicrosoldering** [Repair-DeskPOS/RepairDesk-Bugs#323]
While this issue is new and already noted, it wasn't on github.

Suddenly, the customers email address is mandatory, regardless of configuration. This is effecting every user today.

We now have to enter an email for every job booked in, and there is no way around it

**Comment by Repair-Desk** [comment]
Hello @geelongmicrosoldering, 

It looks like this bug has been squashed! Can you refresh your browser and let me know if you're able to process a transaction?

Usman
