### ISSUE TITLE
Adding more stock using serial no.s

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#33]
Why on Earth do we need to add stock 1st in-order to add serial no's. We should be able to enter the serial no and repair desk will add that stock. e.g. if we enter 10 serial no's then repair desk should automatically add 10 to our inventory from that supplier.
![adding serialised stock](https://cloud.githubusercontent.com/assets/22953208/19590041/19d0ad12-97b3-11e6-8455-2e731e925cca.jpg)

**Comment by Uzair-RepairDesk** [comment]
@TechnologyTraders 
We are going to release Good Receiving Notes (GRN) funtionality next week that will allow you to receive items with reference of Purchase Order (PO) and you will be able to create serials while receiving inventory . Currently its necessary to update stock value if you want to create serials of items. Please do let me know if you are interested in beta testing of GRN functionality on our staging server.

**Comment by TechnologyTraders** [comment]
Sure. That would be great.

**Comment by Uzair-RepairDesk** [comment]
https://repairdeskdemo3.azurewebsites.net
You can login to above staging server with following test account details:-
Username: josh@repairdesk.co
Password: welcome

You can go to Inventory > Goods Received Notes to test GRN functionality.

If you have any other queries/concerns, please feel free to ask. Thanks
