### ISSUE TITLE
Multiple SKU - POS Multi SKUs NOT Unique Per Part

### ISSUE THREAD

**Issue by serfma** [Repair-DeskPOS/RepairDesk-Bugs#330]
Whenever I get to the parts section of the POS and have multiple parts that have multi SKU, it will not allow me to proceed due to "Please select SKU" and every single part that has multiple SKUs have the same two SKUs for them all even though they are different in the inventory section.

Video of the problem
https://www.youtube.com/watch?v=oCa_rSNtazk

**Comment by Repair-Desk** [comment]
Hey @serfma! 👋 Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by usmanalikhan93** [comment]
Hey @serfma! 
I have checked on my end but couldn't reproduce this issue. can you share your account credentials, so I can verify from it? 
usman ali

**Comment by usmanalikhan93** [comment]
Hey @serfma!
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
