### ISSUE TITLE
Clickatell SMS - 2 way kills text notifications.

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-Bugs#331]
Huge bug,
in clickatell settings, if you enable 2 way sms, auto sms notifications are no longer sent. If you uncheck enable 2 way, and select enable api, then sms notifications are restored but you lose 2 way sms.

![image](https://user-images.githubusercontent.com/37640713/40949213-99516238-6832-11e8-8223-760c4c59565f.png)
![image](https://user-images.githubusercontent.com/37640713/40949264-dbc3dc22-6832-11e8-9083-170cae85dc6b.png)

2 way isn't usable if it kills 1 of the 2 ways.

**Comment by Repair-Desk** [comment]
Hey @phonefixdfw 👋 Let us take a look to see if we are getting the same issue as you and we'll circle back to you.

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk We should have Saif look into it

**Comment by Uzair-RepairDesk** [comment]
I have reported it to the development team

**Comment by Repair-Desk** [comment]
@phonefixdfw It looks like this bug has been squashed! Can you create a test ticket and see if you receive SMS notification automatically?
