### ISSUE TITLE
Traduction of "Compliance with GDPR" 

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-Bugs#335]
I want to translate the text "Compliance with GDPR"  in the "Appointment calendar widget" and i cant. Also, is not responsive window for mobiles if you press to read the GDPR. Thanks

**Comment by usmanalikhan93** [comment]
Hi @ireparo!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question. Screenshot is attached. 

Thanks!
![66](https://user-images.githubusercontent.com/39614480/41392203-b77c5d66-6fb8-11e8-8a12-7047f08ab798.png)
