### ISSUE TITLE
Cayan - Multiple Issues

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#336]
Since they won't approve my post, I'll ask on here.... Anyone else having an issue when we complete a payment Via Cayan terminal we get an error saying "Error occurred during payment" then we have to take 5 more minutes to go find there transaction to print a receipt etc. Then majority of the time it's not changing the ticket to "Repaired and collected" so we have about 100 tickets that look like that haven't been completed.

**Comment by githubsucks1** [comment]
Yes, the not closing tickets thing is real. We have to go through and do weekly sweeps which is frustrating.

The double charging is a thing too, but it's random and unless you go through your Cayan gateway portal and.look over every charge, you'll never know.
