### ISSUE TITLE
Problem showing devices in Appointment calendar widget 

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-Bugs#337]
If you enter into the widget (https://ireparo.es/cita-previa-nova/) and press some manufacturer and type something into the searcher devices, if you delete the text of the searcher, don't show all the devices of the manufacturer.

**Comment by Repair-Desk** [comment]
**Hello @ireparo,**

We sincerely apologize for the inconvenience. On the given link I've tried to reproduce the issue however the search function seems to work for me. I've also put together a video [here](https://drive.google.com/file/d/1rZQXeJwYqm2Zg9l366IeGLh0fXIl-Atq/view)

Can you perhaps share a video of this issue so we can look into it for you?

And we hope that if there’s anything else we can do for you, you won’t hesitate to let us know.

Thanks for helping us make this a platform you'll depend on.

Usman Butt
