### ISSUE TITLE
Purchase Orders

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-Bugs#339]
When P.O. is created? Option to print it should be within it. We have to exit and then print it

**Comment by Repair-Desk** [comment]
**Hello @Cumbr1at3ch,**

Thanks a lot for bringing this to our attention. I believe once a purchase order is created we should have similar options in action button in below screen:

<img width="1280" alt="screen shot 2018-06-10 at 7 54 05 am" src="https://user-images.githubusercontent.com/21986026/41201324-b9f81aea-6c83-11e8-96c6-08cf1d6a2615.png">

We've pinned it to our roadmap and will try to release this pretty soon.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Sincerely,
**Usman Butt**

**Comment by usmanalikhan93** [comment]
Hey @Cumbr1at3ch!

It looks like this bug has been squashed! Can you give it a try? And do let us know if you have any  question. :)
Thanks!

**Comment by usmanalikhan93** [comment]
Hey @Cumbr1at3ch!

It looks like this bug has been squashed! Can you give it a try? And do let us know if you have any  question. :)
Screenshot is attached. 
Thanks!
![72](https://user-images.githubusercontent.com/39614480/41402752-97360560-6fdc-11e8-98db-fb54d9d45142.png)
