### ISSUE TITLE
Sales tax switches from Taxing on part to taxing whole sale

### ISSUE THREAD

**Issue by CandiceQuikFix** [Repair-DeskPOS/RepairDesk-Bugs#340]
At first the sales tax is only taxing on the part, but every time I try and edit a ticket or invoice the sales tax seems to switch from taxing on the part to taxing on the whole sale. From there I have to manually edit it, but if I add something or change the ticket/ invoice again, it will again switch to taxing on the whole price.

**Comment by Repair-Desk** [comment]
Hello @CandiceQuikFix 

We sincerely apologize for the inconvenience. 

Can you please confirm if you want to charge tax on the entire repair or just parts only?

Look forward to hearing back from you.

Sincerely,
**Usman Butt**
