### ISSUE TITLE
Again the Same problem

### ISSUE THREAD

**Issue by allbbadstore** [Repair-DeskPOS/RepairDesk-Bugs#345]
Hello friends
The problem is always repeated when performing some operations in the departments
Taking into consideration the main user and administrative:
The error message!
"Something Went Wrong"

<a href='https://postimg.cc/image/yztrccq0b/' target='_blank'><img src='https://s33.postimg.cc/yztrccq0b/9_EA4_C66_B-97_B1-4_CAC-_A216-812_E9_ABCC54_E.jpg' border='0' alt='9_EA4_C66_B-97_B1-4_CAC-_A216-812_E9_ABCC54_E'/></a>

### **Please fix the problem 
my regards**

**Comment by Repair-Desk** [comment]
Hey @allbbadstore  👋 Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by Repair-Desk** [comment]
It looks like you were trying to add a payment method in "Arabic" and the field didn't support that. This bug has been squashed! 

@allbbadstore Can you refresh your browser and let us know if you're able to process a add a new payment method?

And I hope that if there’s anything else I can do for you, you won’t hesitate to let us know.

Thanks for helping us make this a platform you'll depend on.
