### ISSUE TITLE
Cayan Payment Screen NOT displaying

### ISSUE THREAD

**Issue by AccessOneSales** [Repair-DeskPOS/RepairDesk-Bugs#346]
After creating a sale or ticket payment screen does not consistently show on the cayan display

**Comment by Repair-Desk** [comment]
**Hello @AccessOneSales,**

Happy to help with this however we would a bit more information before we can confirm if there is an issue with our integration with Cayan or the problem with Genius terminal.

**Here's what I would recommend:*
1- Have a look at Cayan knowledge-base to see if they already have a solution for it.

2- Share a video of test transaction using your mobile that shows RepairDesk and Cayan terminal so we can forward it to our product team and they can resolve a fix for it.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**Usman**
