### ISSUE TITLE
Diagnostic w/Payment Option

### ISSUE THREAD

**Issue by AccessOneSales** [Repair-DeskPOS/RepairDesk-Bugs#347]
Need RD system to not close the ticket after taking a payment for a diagnostic fee and system automatically update the status to repaired/collected and also send completed email to the customer.

**Comment by Repair-Desk** [comment]
**Hello @AccessOneSales,**

We've put together a quick video that shows how you can take a deposit. Here is a video [link](https://drive.google.com/file/d/1Wm9Fphuffr_pfCctsFgLrm01tzEzZuJS/view)

If you are taking diagnostic fee deposit against an existing repair ticket and don't want work order status to be marked as "repaired and collected" from the checkout pop up here's what you need to do:

![notification](https://user-images.githubusercontent.com/21986026/41682022-ebbfad30-74ef-11e8-995f-75b5392a4d19.png)

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Usman
