### ISSUE TITLE
Uploading customer CSV

### ISSUE THREAD

**Issue by Raheel-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#35]
Dear, 

   Please add the functionality of uploading max customers through one CSV file, 

Regards,

**Comment by Repair-Desk** [comment]
@muhammadfayyaz3 As discussed with @aishahanif please get it fixed by tomorrow.

**Comment by muhammadfayyaz3** [comment]
Dear @aishahanif issue fixed. kindly make it live after review.
