### ISSUE TITLE
Take a Credit Card over the phone

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-Bugs#353]
I'd like to think this is a pretty basic feature that should already be apart of repair desk.  Without this system, we are forced to take credit cards with an outside provider that doesn't link with repair desk. It throws off everything.

**Comment by Repair-Desk** [comment]
**Hello @TPRS** 

Happy to help you with this. We've an integration with Stripe using which you can take credit card payments over the phone.

You can learn more about it **[here](https://repairdesk.uservoice.com/knowledgebase/articles/872658-how-to-start-accepting-credit-card-payments-with-s)**
