### ISSUE TITLE
GRN inventory labels show $0.00 if you print all

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-Bugs#354]
if you 'print selected labels' (some or all) from the popup after you receive GRN, it makes inventory label show $0.00. 

if you select the printer next to item in list and print 1 by 1, it shows correct price.
![printsingle](https://user-images.githubusercontent.com/37640713/42117466-47dadca6-7bc2-11e8-9589-bb85a2c36067.PNG)
![printall](https://user-images.githubusercontent.com/37640713/42117467-47e9697e-7bc2-11e8-8cd7-fca1d9560ff5.PNG)

**Comment by Repair-Desk** [comment]
Hey @phonefixdfw! 👋 Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by usmanalikhan93** [comment]
Hello @phonefixdfw!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
usman ali

**Comment by phonefixdfw** [comment]
appears working, thanks

*9034 Garland Rd, **Dallas TX 75218*


*7340 Highway 78, Suite 260, Sachse TX 750481616 N State Highway 161, Grand
Prairie TX 75050*
*972-587-7433 <https://mail.google.com/mail/u/0/>** | www.phonefixdfw.com
<http://www.phonefixdfw.com/>*
