### ISSUE TITLE
commission calculations include tax

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-Bugs#362]
If an item is $10 plus 8% tax, a 10% commission shows at 1.08 because it calculates on the total taxed amount. It should calculate pre tax amount. No one pays commission on tax. at least make it an option.

**Comment by Repair-Desk** [comment]
**Hello @phonefixdfw** 

Thanks a lot for sharing your feedback. We are re-writing commission module and this is already part of the improvements we are working on.

I will close this thread and will keep you posted on the progress through IM.

Regards,
Usman

**Comment by Uzair-RepairDesk** [comment]
Already listed task #265 
Its included in "Employee Commission Module" improvements. 
Reference Task JIRA: RD-31
