### ISSUE TITLE
Transfer Order Issues

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#37]
We are facing some issues with Transfer Order function.

1. Transfer stocks from Store A to Store B has error message below
Please fix the following input errors:
Recieved By cannot be blank.
Where the fieldl Received By is grayed out, cannot input.

![image](https://cloud.githubusercontent.com/assets/22993605/19617476/5f8d3ac6-987d-11e6-9bad-1ad45e032e74.png)

2. Transfer from Store B to Store A.
The Employee filed is Empty, cannot select any one.

![image](https://cloud.githubusercontent.com/assets/22993605/19617478/6d097278-987d-11e6-9a80-20a6a56bc92a.png)

Please look into this since it is stopping our day to day duties. Used to work perfectly fine but now playing up.

**Comment by muhammadfayyaz3** [comment]
Dear @aishahanif @Fazal-RepairDesk Issue fixed.

**Comment by Uzair-RepairDesk** [comment]
@HafizAnas can you please review this?

**Comment by quangc** [comment]
Confirmed that the issues are fixed, all working today.

**Comment by HafizAnas** [comment]
Fixed, It's working fine.
