### ISSUE TITLE
Pattern Lock For Android Phones

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#38]
There should be a way to store pattern lock for android phones

**Comment by Repair-Desk** [comment]
@itskamran once sajjad gets free can you have him develop this one?

**Comment by Fazal-RepairDesk** [comment]
'Saving Pattern Lock for Android Phone' functionality has been added to RepairDesk and is live. 
To know about how this functionality works, please refer to this article: https://repairdesk.uservoice.com/knowledgebase/articles/1148578-how-can-i-save-an-android-phone-pattern-lock
