### ISSUE TITLE
Cost of cell phones are not calculating in Rd reports.

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#39]
This is in reports by type
![14680489_10205991190013839_4139061474708051876_n](https://cloud.githubusercontent.com/assets/21986026/19634266/d2463486-99d2-11e6-856c-9b52ce5c2deb.jpg)

**Comment by Uzair-RepairDesk** [comment]
Issue Reported by Michael ST John on Facebook User Group

**Comment by muhammadfayyaz3** [comment]
@Uzair-RepairDesk problem is something else, User do not has permission to view Cost Price that's why in every invoice cost price is 0 and that affect shows in Report.
Kindly Give Show Cost Price Permission to that specific Role. then It works fine.

**Comment by muhammadfayyaz3** [comment]
@aishahanif I have made some changes in UserRights Model kindly make it live.
Revision #662, Branch v1.9.2.7

**Comment by hafeezshahid** [comment]
Issue Fixed and reviewed.
