### ISSUE TITLE
Template Editor Issue

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#41]
"Miko" from "Campus Mobile Solution" 
He is still facing the following issues:-
1: When customer opens "Mini Receipt" from template editor. He is facing the error 500 issue.
2: He has edited canned response of High Five. It display edited canned response in ticket section but when customer sends email, it doesn't display correctly. Please have a look at screenshot attached. Can you please it so if customer edit any canned response, it should not create any problem
3: In case of Walk in widget, "Thank you" confirmation message popup goes below the screen.

Can you please fix above issues. Thanks. 
![mini receipt template editor error](https://cloud.githubusercontent.com/assets/22955861/19634987/5d6e3cc0-99d8-11e6-8c2e-962a5b8ea251.jpg)
![actual canned response](https://cloud.githubusercontent.com/assets/22955861/19634989/5d728c1c-99d8-11e6-932a-e45672c533fe.jpg)
![email canned response](https://cloud.githubusercontent.com/assets/22955861/19634988/5d7068ce-99d8-11e6-8d17-7ab4c2b05641.jpg)

**Comment by aishahanif** [comment]
1. mini receipt template is working fine.
2. in email templates he did a complete change in html and css that creates the problem as discussed every email server has different settings to cover. thats why he is facing problem.
3. not reproduce. i have checked his store script in  a web page and it shows in the center of page. 
please share his testing page link to verify the problem.
