### ISSUE TITLE
Issue With Role

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#46]
I've created a new store profile & when you try to **[update personal profile](https://app.repairdesk.co/index.php?r=user/profile)** it gives attached error

![profile](https://cloud.githubusercontent.com/assets/21986026/19658271/cac836b4-9a40-11e6-9ac6-3226972bd134.png)

**Comment by muhammadfayyaz3** [comment]
Dear @aishahanif issue has been fixed. kindly find Revision # 642, Branch v1.9.2.7
