### ISSUE TITLE
Printnode label only auto-printing one device

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#47]
Hey Guys,

When we add more than one device to the same ticket Printnode only auto-prints the 1st device on the ticket. We then have to manually select the 2nd device and print label manually to our label printer. Please refer to ticket no.: CPT-2472.

**Comment by Uzair-RepairDesk** [comment]
Hey there,
Imran will fix this issue once he come back from his holidays. It is expected to be fixed in 2nd Milestone Release.

**Comment by HafizAnas** [comment]
Hey @TechnologyTraders 
I have tested at my end and it's working fine. Please can you check at your end and share screenshots or video with us if you still have any issue. Thanks
