### ISSUE TITLE
Repairdesk calculating different values

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#48]
Hey Guys,

This ticket was updated from 'diagnostics' for $50 to 'Battery Replacement' for $150.00. During the 1st update it will some how calculate the tax value wrongly. In such case we need to save the ticket and re-edit to get the correct value..

![wrong values](https://cloud.githubusercontent.com/assets/22953208/19666994/4a6dc37a-9a91-11e6-850f-f3f8fd870bf0.jpg)
![reedit fix wrong values](https://cloud.githubusercontent.com/assets/22953208/19666995/4be20b4e-9a91-11e6-9185-025ca38fba2f.jpg)

**Comment by HafizAnas** [comment]
@imiamran 
Please have a look this issue. It usually happens due to change tax class or price.

**Comment by Uzair-RepairDesk** [comment]
@TechnologyTraders 
The above reported issue has been fixed and live now. Please review at your end and do let me know if further assistance required. Thanks
