### ISSUE TITLE
Serialised item does not get back In Stock after Refund

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#49]
Please be investigate the case that Refund Item does not become In Stock but it is still showing as Sold in our Inventory. Our staff had to Delete that Serial and Re-Create that Item which should not be the way.

**Comment by muhammadfayyaz3** [comment]
Dear @quangc
Everything  is  working fine on our end kindly do check it again.

**Comment by hafeezshahid** [comment]
Please look into the exisitng issues according to our discussion today.

**Comment by HafizAnas** [comment]
Hi @quangc 
Thanks for your patience, I am glad to inform you that your reported issue has been fixed and it's working fine at my end.  there is only thing " If technician/admin use any serialize part against repair ticket and refund it later, this part will not be added back into stock" 
we are working to improve it and hopefully we will fixed it with best solution asap.
