### ISSUE TITLE
Supplied items not appearing on Ticket

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#5]
When the customer selects supplied items just before checkout, even though if all are selected, only two supplied items are displayed on the ticket: sim card, memory card. 
Kindly see the ticket mini receipt and screenshot attached below

![](https://cloud.githubusercontent.com/assets/21986026/19548356/6dd7337e-96b7-11e6-913d-933327bb87a2.png)
[Supplied.Items.Sajid.pdf](https://github.com/Repair-DeskPOS/RepairDesk-Bugs/files/541250/Supplied.Items.Sajid.pdf)

**Comment by Fazal-RepairDesk** [comment]
@aishahanif Sajid is asking for an update. What's the status?

**Comment by Repair-Desk** [comment]
@aishahanif Please ask Sajjad to update design for custom supplied items. Right now it appears in one line and overlaps
