### ISSUE TITLE
Issue while switching users

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#50]
When the same user signs up in two windows, then while switching users its working fine. But when the user logs off from one of the windows, a different list of several users pops up. @aishahanif  your name aslo shows up on the list. However once the user signs up again in the second window, the usual number of users appear. 
Customer: Jonathan White
Business: Think Digital

He has submitted a video of the process. 
@HafizAnas can you please show it to Ms. @aishahanif as it is on intercom. 

Link: https://uploads.intercomcdn.com/i/o/12180694/a0d092261524f91bafc17679/RepairDesk.webm

**Comment by hafeezshahid** [comment]
Reviewed on staging, issue fixed.
@aishahanif  please make it live.
