### ISSUE TITLE
Issue when Updating tickets

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#52]
Hey Guys,

Please refer to Ticket no. CPT-2454. Originally generate via POS, Device: PC & Mac and Task: Diagnostics, for $50.00. I changed the Task from 'diagnostics' to 'data recovery' which went smoothly and total cost was all good this time round. The problem I encountered, was when I added an inventory item it refreshed the page and reset the task back to 'diagnostics' before I could save the ticket. I essentially have to add the inventory item 1st then update the task. Otherwise, I am doing the same thing twice.

**Comment by Repair-Desk** [comment]
@HafizAnas can you check this issue and assign it to a developer

**Comment by HafizAnas** [comment]
@imiamran @aishahanif 
Please have a look attached screenshots for more understanding.

![add-item1](https://cloud.githubusercontent.com/assets/22954115/20474729/e373476c-afe9-11e6-808b-71869fa07c84.png)

![add-item2](https://cloud.githubusercontent.com/assets/22954115/20474735/eb3c82ec-afe9-11e6-92f5-6ecda3f82854.png)

**Comment by itskamran** [comment]
Dear @TechnologyTraders,

Issue has been resolved. Thanks
