### ISSUE TITLE
Invoice not searchable in POS Refund Tab

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#53]
When the user tries to refund an invoice from the Refund Tab in the POS section, the invoice is not searchable. No results found. Even though if the invoice exists in the list of invoices from the View Invoices  Tab. 

Customer: Arno
Business:  Dr. Smartphone

**Comment by Fazal-RepairDesk** [comment]
What's the update? Mam @aishahanif @hafeezshahid @HafizAnas

**Comment by HafizAnas** [comment]
@aishahanif 
Please have a look this issue on urgent basis.

**Comment by aishahanif** [comment]
@HafizAnas  please review the fix on staging
