### ISSUE TITLE
Rounding issues to values calculating tax on top of input values

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-Bugs#54]
Hey All,

Just recently we have been facing some weird issues in POS. Ticket in question is CPT-2472. Brought it forward in to POS. 1st value is $25.00 and 2nd value is $80.00, a total of $105.00 inclusive of TAX. Somehow 1 cent is added to the total. I adjusted the values in POS as above and RD added tax on top of $105.00 when it should have calculated prices to a total of $105.00. Please refer to the screen recording dsent to your group via voice chat 25-10-2016.

**Comment by Repair-Desk** [comment]
@HafizAnas can you review at your conveneince.

**Comment by HafizAnas** [comment]
@aishahanif 
Client has reported this again. Please have a look this issue on urgent basis. See more details and screenshot from given link below.

https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/32

**Comment by itskamran** [comment]
Dear Technology Traders,

Issue has been resolved, so kindly test at your end and let us know if there is any problem. Thanks

**Comment by itskamran** [comment]
Dear @TechnologyTraders, 

Mentioned issue is  working fine.
Kindly verify at your end and in case of any problem share the values against which you are facing rounding issue. Thanks
