### ISSUE TITLE
Cannot add Ticket Item

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#55]
Just found another issue with adding ticket item. The Action button does not have any menu items, but showing another Action menu.

The Add Line Item at below also not clickable. Nothing happens when clicking it. Refer the below Screenshot.

![image](https://cloud.githubusercontent.com/assets/22993605/19708479/8feb46f0-9b6a-11e6-9986-18ffe9753f5a.png)

**Comment by Repair-Desk** [comment]
@aishahanif can you check and fix it Asap

**Comment by Repair-Desk** [comment]
@quangc sorry for inconvenience and i will try to get it fixed in few hours!

**Comment by Repair-Desk** [comment]
**@quangc** reported issue has been fixed. Please verify it on your end.
