### ISSUE TITLE
Trade-in reciept template editing [enhancement]

### ISSUE THREAD

**Issue by simardm** [Repair-DeskPOS/RepairDesk-Bugs#57]
Hi, I need to edit the template to traslate elements on the reciept. So far, i was able to edit every other reciept that we needed but now we need the trade-in to be in our local language, for legal reasons.

**Comment by simardm** [comment]
Also, it would be nice if the description field would stick trough reciepts, so that if we have to comment what details those devices have (like if I want to say that an iPhone wont have it's touchID working) so it could convert into a public comment on the reciept. It would be easier for the seller to disclose things about the device (like in this case, to warn a customer the iPhone wont have touchID and he can't get refunded afterwards under a warranty)

**Comment by HafizAnas** [comment]
@simardm 

 Your requested changes (Template Editor Mini Receipt for Trade In) has been done. Kindly check at your end and do let us know if you have any question. I am going to close ticket for now
