### ISSUE TITLE
Transferred ticket is still showing in original store

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#58]
We've transfered a ticket from a store to another and it is now showing in both store. Please see screenshots below.

![screen shot 2016-10-27 at 5 11 58 pm](https://cloud.githubusercontent.com/assets/22993605/19756666/0e603b3a-9c6a-11e6-8b6a-f9ebedcc93ca.png)
![screen shot 2016-10-27 at 5 12 20 pm](https://cloud.githubusercontent.com/assets/22993605/19756667/0eb06196-9c6a-11e6-807e-623928fbb945.png)

**Comment by Repair-Desk** [comment]
@quangc when you transfer ticket from one store to another store it doesn't remove it from original store rather update its status to in-house transfer on original store.

@hafeezshahid @HafizAnas can you check this issue?

**Comment by hafeezshahid** [comment]
@quangc According to our functionality at the moment, When you transfer ticket from one store location to another, the ticket will show in both store locations with the status of in house transfer and when you transfer that ticket back to the original store it will change the status to pending.

Please refer to the following article for further queries https://repairdesk.uservoice.com/knowledgebase/articles/921240-how-to-transfer-ticket-from-one-store-to-another-l
