### ISSUE TITLE
Additional notes bound to a Customer's file. [enhancement]

### ISSUE THREAD

**Issue by simardm** [Repair-DeskPOS/RepairDesk-Bugs#60]
It would be nice if we could add some form of comments tied to the Costumer's file, like adding credits to his file (like a promotion buy this and receive this many credits towards a future repair or accessory), or explaining if he has an aggressive temperament (could be!). Point is, in a multi employee environment, details about a specific costumer gets lost. Would be nice also if theres information in the comment field it would have an icon or something to tell the employee it has comments on file (see screencap below).

![eureka mobile pos](https://cloud.githubusercontent.com/assets/23082016/19782326/5b2bb732-9c5b-11e6-916e-2848e430e29c.png)

Thanks a lot!

**Comment by Uzair-RepairDesk** [comment]
Hi There,
Its a good idea, We can add "Notes" filed in customer details so admin/user can enter comments for a particular customer. 
We will keep in mind once we proceed with updating customers module and add "Pricing for Wholesale Customers" feature in RepairDesk. 
We can expect to add it in 4th Release of November.

**Comment by Fazal-RepairDesk** [comment]
Issue already resolved and is on live. Closing it here.

**Comment by Fazal-RepairDesk** [comment]
Issue already resolved and is on live. Closing it here.
