### ISSUE TITLE
Customer Facing Display - Issue 

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#62]
You can still hit confirm without ticking the agree to terms checkbox. It shouldn't let you submit the form if it's either not signed and/or that checkbox isn't ticked.

Also make landing & order detail page translatable.

**Comment by qn1715** [comment]
Its working fine with signature and term & condition validation on order detail form view
![order-form](https://cloud.githubusercontent.com/assets/22954560/19956617/85d4ca50-a1b0-11e6-88b4-a8123d48dd29.png)
.
