### ISSUE TITLE
issues with capalaba store (End shift + Transaction Log)

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#63]
Capalaba Admin reported two issues:
1. Booval store had an error while trying to end shift just after 7pm 
2. Toowong and Capalaba stores cannot access trans log or end shift
![capalaba_shift](https://cloud.githubusercontent.com/assets/22954033/19795614/9d81e674-9cf6-11e6-8ac4-55c350e6873d.png)

**Comment by Uzair-RepairDesk** [comment]
Issue has been fixed
