### ISSUE TITLE
Ticket Listing - Update Due Date & Time Error Message

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#64]
You get an error when you try to update or change due date or time on tickets listing page.

But if you refresh it updates the record however it just errors for no reason.

Also the error has a typo (spelling mistake)

![image](https://cloud.githubusercontent.com/assets/21986026/19797196/0845d4aa-9d03-11e6-9f4b-99170e986a83.png)

**Comment by HafizAnas** [comment]
@imiamran 
I have reviewed, there is something wrong when admin/user update Due Date on listing page

**Comment by imiamran** [comment]
issue has been fixed.

**Comment by imiamran** [comment]
@HafizAnas issue has been fixed
