### ISSUE TITLE
Enhancement: Purchase Order showing one column with payment status

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#65]
It will be nice if there is extra column to show the payment status for Purchase Orders so we can quickly pinpoint to the one which is not paid or partial paid.

This will save our time to View every single PO to find out if it has been paid or not. If there is other ways please advise.

**Comment by Repair-Desk** [comment]
@quangc Sounds like an interesting option. We would be able to look at it at the start of next year. At this point our goal is to fix existing bugs and improve application speed.

**Comment by aishahanif** [comment]
@HafizAnas  said enhancement is live on staging for QA review.

**Comment by Repair-Desk** [comment]
@muhammadfayyaz3 Can we move payment status so its less confusing?

![po](https://cloud.githubusercontent.com/assets/21986026/20313333/728470f0-ab78-11e6-9269-51db01ef3474.png)

**Comment by HafizAnas** [comment]
@muhammadfayyaz3 
Please have a look above feedback and screenshot
