### ISSUE TITLE
Roles is not working properly

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#66]
We have setup few Roles and one Role which is Technician has very limited access to Settings and Admin Functions. We are having 2 Staffs under this Role and yet they can access all Settings and other functions as Super User.

Please investigate since we don't want our staffs to see our sensitive information.

**Comment by Uzair-RepairDesk** [comment]
@muhammadfayyaz3 
I have checked Quang account. He has 2 users under Technician role with limited access. He is saying that technicians are still able to access restricted areas. Can you please check and fix it.

**Comment by muhammadfayyaz3** [comment]
@Uzair-RepairDesk let me check it.

**Comment by quangc** [comment]
Any updates @muhammadfayyaz3 ?

**Comment by muhammadfayyaz3** [comment]
@quangc issue fixed. 👍

**Comment by quangc** [comment]
All good!!!
