### ISSUE TITLE
Edit lead email template

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#67]
You should be able to edit email template that is sent to a customer and administrator once a customer fills up a form using repair booking booking

**Comment by Repair-Desk** [comment]
@muhammadfayyaz3 A lot of customers has requested this feature recently. Can you please add it to your task list?

**Comment by Repair-Desk** [comment]
@muhammadfayyaz3 can we add it to RepairDesk first thing Monday morning
