### ISSUE TITLE
Stock does not added into Inventory after GRN is done

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#68]
We've just found out that our stock does not get updated after GRN is done.

Refer to below screenshots. Screenshot 1 showing the latest update into inventory for an item. Screenshot 2 showing the lasted Purchase Order which contains 10 items and after GRN, these 10 items did not get added into Inventory as in the Screenshot 1 shows.

<img width="1040" alt="stock update issue 1" src="https://cloud.githubusercontent.com/assets/22993605/19841210/7315062a-9f5b-11e6-8578-e99d002d9f06.png">
<img width="1269" alt="stock update issue 2" src="https://cloud.githubusercontent.com/assets/22993605/19841209/7314b616-9f5b-11e6-83a1-2b32afa858f2.png">

**Comment by quangc** [comment]
It may got updated into Inventory but did not showing up in the Admin History.

**Comment by Repair-Desk** [comment]
@HafizAnas Can you check this and assign it to developer

**Comment by muhammadfayyaz3** [comment]
@Uzair-RepairDesk Issue fixed. GRN actually working fine but It didn't update admin history.
Miss @aishahanif kidnly find Revision # 680, Branch v1.9.2.7

**Comment by Repair-Desk** [comment]
@muhammadfayyaz3 Thanks for your prompt action
