### ISSUE TITLE
Disable / Remove Default Ticket Status

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#7]
There should be a way to disable default ticket status so it doesnt appear in dropdown

![](https://cloud.githubusercontent.com/assets/21986026/19548858/6090e676-96ba-11e6-88b4-0a4bf46aacf7.png)

**Comment by RepairDeskPOS** [comment]
You should be able to edit default status

**Comment by Repair-Desk** [comment]
@HafizAnas I can't seem to disable default ticket status.

**Comment by RichieRichNZ** [comment]
I would also like to see this done. I only use a third of the defaults and would rather remove the ones we dont need. Would also be good to modify the colours of the defaults as well.

**Comment by Repair-Desk** [comment]
@itskamran can we get this done in December release?

**Comment by Repair-Desk** [comment]
Option to hide default ticket status has been added. 

![how to disable default ticket status](https://cloud.githubusercontent.com/assets/21986026/21541281/e086741a-cdd6-11e6-9e54-6740650a9054.png)
