### ISSUE TITLE
GRN make PO Partially Received

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#70]
This issue is just happens now. After create GRN fully received stock, the PO become Partially Received instead of Received.

Please look into this. Used to work fine before.

![grn issue](https://cloud.githubusercontent.com/assets/22993605/19845974/122f0c7c-9f90-11e6-81cc-35b76a4b4ffa.png)

**Comment by Uzair-RepairDesk** [comment]
@muhammadfayyaz3 
As discussed, can you please check and fix this issue

**Comment by muhammadfayyaz3** [comment]
Dear @quangc you are adding same item with different cost price and description that is creating the problem. If you have one item please do not add it multiple times in purchase order PO or if you have different description of an item, I recommend you to add separate item in the inventory and then add it into PO to avoid this problem. 
If we update the same item, cost price doesn't justify or update for the same item, please have a look on attachment
![repair centre springvale - view purchaseorder](https://cloud.githubusercontent.com/assets/22974191/19996032/6a0659c8-a27e-11e6-9a90-3075211d94f6.png)

**Comment by hafeezshahid** [comment]
@Fazal-RepairDesk Please read the above comments by @muhammadfayyaz3  and update customer.

**Comment by Uzair-RepairDesk** [comment]
@quangc 
You can read @muhammadfayyaz3 comment to get understanding regarding this issue.

**Comment by quangc** [comment]
Just get back to this issue since we have the reason that we will need to have different prices for the same item. Please see the below screenshot. We serialised our inventory in a way to  optimise the database so we have created one item as iPhone 6 and inside the serials, we then distinct the Capacity, Colour, Conditions, etc. So the prices are different if the Capacity is different, for example 16GB phone will be cheaper then 128GB as can be seen in the screenshot. We do not want to create many items for the same product, this will make our database bigger and slower.
Any ideas to go around this?
<img width="753" alt="screen shot 2016-12-02 at 2 37 51 pm" src="https://cloud.githubusercontent.com/assets/22993605/20822315/cc11dae0-b89d-11e6-9584-b687b94d85e2.png">
