### ISSUE TITLE
Cannot see Cost price for Items with owner account

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#71]
It got fixed recently but happens again today. My account cannot see Cost Prices.

<img width="737" alt="screen shot 2016-10-31 at 8 34 06 pm" src="https://cloud.githubusercontent.com/assets/22993605/19849879/9dc1935e-9fa9-11e6-9c02-3bdf6472760c.png">

**Comment by muhammadfayyaz3** [comment]
Dear @Uzair-RepairDesk Issue fixed. @aishahanif kindly update Rev# 681, on live.

**Comment by quangc** [comment]
Any updates on this issues @muhammadfayyaz3 ?

**Comment by muhammadfayyaz3** [comment]
@quangc issue fixed.
