### ISSUE TITLE
Phone number extentions [bug]

### ISSUE THREAD

**Issue by simardm** [Repair-DeskPOS/RepairDesk-Bugs#73]
Some of our costumers need to be called when they're at work, but they have extentions. They seem to be supported but they dont actually work. The field stops adding numbers once the [ext.] appears. And then a weird error happens. See screencap below. (Note: Screencap shows a 1-418-555-5555 but the problem persists with any other phone number)

![eureka mobile pos_phoneissues](https://cloud.githubusercontent.com/assets/23082016/19863480/c23632d8-9f6a-11e6-8be1-e4e634f8b7cd.png)

**Comment by RepairDeskPOS** [comment]
We are using Google Api which automatically check if entered number is valid or not.

Please ensure when entering mobile or phone number it doesnt starts with 0.

Also dont enter mobile number under phone column

Incase it doesnt show country flag type +1
Hope it helps

**Comment by simardm** [comment]
As you can see on screencap, the numbers format is correct, doesnt start with 0, we ask the costumer wether it's a mobile or landline number, but we cant add extentions. It stops adding numbers after the 10th number is entered and it puts the [ext.]. I can try any number other than 418-555-5555 or 418-555-5556 and I still have the same problem. And also the API is unreliable, once we tried to reach a client and the number wasnt in service, even though it said valid.

**Comment by RepairDeskPOS** [comment]
The Api doesnt allow you to add extension at this point.

Secondly it doesnt check if the number is in service or not but just validate number format.

**Comment by simardm** [comment]
Oh ok, thanks for the info.
