### ISSUE TITLE
Issue with commission report

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#74]
Every employee making same commission?? This is incorrect

**Issue Reported By: Michael St John**

![commission](https://cloud.githubusercontent.com/assets/21986026/20057187/080831ca-a50c-11e6-9012-03644eac86a8.jpg)

**Comment by HafizAnas** [comment]
@aishahanif 
Please have a look this issue from client account if you have credential because I am not able to reproduce this issue at my end.

**Comment by muhammadfayyaz3** [comment]
Dear @hafeezshahid I just checked @Michael account and found this report perfect like I attach screen below. Would you please check at your end.
![cv cellular solutions employee commission report](https://cloud.githubusercontent.com/assets/22974191/20131063/cdf1af1c-a67c-11e6-8bba-b6214796581c.png)

**Comment by hafeezshahid** [comment]
@Fazal-RepairDesk  Please contact customer, as we are not able to generate this issue at our end.
