### ISSUE TITLE
Lead Notification Error + Default Spanish Error

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#75]
Customer: Admin | Movilsat
When the customer books a repair from the repair booking widget, a lead generation notification appears on the bell shaped notification icon. When the user opens the notification an error message opens (Please see the screenshot attached). I've checked it. I get the same error from user's account. 
![movilsat_3](https://cloud.githubusercontent.com/assets/22954033/19927248/b9d75b38-a11a-11e6-8de7-74c932ba1ed3.png)

Also the user is facing the issue when setting the Spanish language as default. When the user selects the spanish language and makes changes, the changes are not saved (please check, I did and it worked)

**Comment by Fazal-RepairDesk** [comment]
Any update? @HafizAnas @hafeezshahid

**Comment by hafeezshahid** [comment]
@imiamran Please look into this issue, when booking a ticket from repair booking widget, the user gets a notification and when the user clicks on the notification on POS it returns the error as shown in above screenshot.

**Comment by Repair-Desk** [comment]
@imiamran can you fix it by Tuesday please

**Comment by HafizAnas** [comment]
@Fazal-RepairDesk 
I have reviewed it again, it's working fine now.
