### ISSUE TITLE
Exporting Customers Error 403

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-Bugs#76]
If customer list contains more than 5000 customers it gives error

**Comment by Repair-Desk** [comment]
@hafeezshahid can you check this bug?

**Comment by hafeezshahid** [comment]
@Repair-Desk This is a duplicate issue with issue #30 ,this issue is fixed on staging and reviewed as well, waiting for it to go live.
https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/30
