### ISSUE TITLE
Problem creating new customer - cant add phone number

### ISSUE THREAD

**Issue by fetchwireless** [Repair-DeskPOS/RepairDesk-Bugs#77]
When creating a new customer as of today we can no longer add the phone number.  the phone number drop down is stuck on the flag for a particular country code and the number entry box will not allow any text to be entered.

**Comment by Repair-Desk** [comment]
@fetchwireless we are using Google API for phone and mobile number verification. Sometimes due to high traffic it doesn't display country flag by default.

If it happens please enter the number in international format. i.e. +1 3109281115

In the meantime we will look for alternative.
