### ISSUE TITLE
Manual Out  does not consistently work

### ISSUE THREAD

**Issue by fetchwireless** [Repair-DeskPOS/RepairDesk-Bugs#78]
When performing a manual out a notice appears saying reason cannot be blank, even when there is text in the reason box.  Sometimes the manual out amount is subtracted. Sometimes does not get subtracted.

**Comment by Repair-Desk** [comment]
@HafizAnas can you please test if reason support special character and also double check why the cash out amount is not subtracted on continuous basis

**Comment by HafizAnas** [comment]
Hi @fetchwireless 

I have double checked at my end it's working fine at my end. I am not able to reproduce this issue again.
Please check at your end and share steps or screenshots if you are still facing this issue. (See Screenshot)


![a manual in out history](https://cloud.githubusercontent.com/assets/22954115/20056932/7e99ea74-a50a-11e6-9e1f-fb5b71a643ab.png)

**Comment by fetchwireless** [comment]
I did 2 yesterday and right now it is working fine.  The issue is that it
will work fine some days and others it will not.  Some days it will behave
like it accepted the transaction but does not.  Other days it will give the
error.  The next time it does this I will try to capture it with a
screenshot or video.

**Comment by Repair-Desk** [comment]
@fetchwireless Please share a video when it happens again so we can look into it.

@HafizAnas can you mark it as closed please?
