### ISSUE TITLE
Searching for product on POS search

### ISSUE THREAD

**Issue by fetchwireless** [Repair-DeskPOS/RepairDesk-Bugs#80]
On POS search when typing in a barcode id or key word, the search function is very slow.  Sometimes taking a minute or more to find the item we are searching for.  This is a big issue.  It significantly slows down checkout.  Sometimes it will error and say the product is not there at all but it then displays the second time we search for it.  Search should take no longer than a few seconds per line item.

**Comment by Repair-Desk** [comment]
@fetchwireless can you put together a quick video and share a link here as we don't get speed issue on our end?

**Comment by imiamran** [comment]
this issue has been fixed 3 days ago .
