### ISSUE TITLE
Terms & Conditions not appearing on Receipt

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#83]
Customer: Zarna | GR Phones
When the customer prints the mini receipt, the terms and conditions are not displaying on the receipt. I've checked it myself as well. The Terms and Conditions are written and saved in the receipt
![zarna_gr phones_tc_receipt](https://cloud.githubusercontent.com/assets/22954033/19998195/46eb8c92-a28d-11e6-90bc-b752a62f8b9f.JPG)
![zarna_gr phones_tc_receipt2](https://cloud.githubusercontent.com/assets/22954033/19998196/46f43004-a28d-11e6-8613-778719f0c144.JPG)

 module although.

**Comment by Fazal-RepairDesk** [comment]
@HafizAnas @aishahanif any progress??

**Comment by hafeezshahid** [comment]
@Fazal-RepairDesk Issue Fixed and Reviewed, please update the customer.

**Comment by Fazal-RepairDesk** [comment]
@hafeezshahid @HafizAnas customer is still facing the issue

**Comment by Repair-Desk** [comment]
@HafizAnas any update on this one?

**Comment by Uzair-RepairDesk** [comment]
According to Mam Aisha, Issue has been fixed and working fine on live
