### ISSUE TITLE
Serialised inventory issues with Status

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-Bugs#84]
Our inventory does not show the right Status. Please see below screenshot. It is none left in stock but inside the item it is still showing 5 items In Stock. The first item is actually transferred to another store which also has issue which will be posted in a separate thread. The last 4 items are sold long time ago.

<img width="1249" alt="screen shot 2016-11-05 at 4 53 46 pm" src="https://cloud.githubusercontent.com/assets/22993605/20028011/47395ae8-a379-11e6-8248-d1d69e5c84e5.png">
<img width="1155" alt="screen shot 2016-11-05 at 4 55 07 pm" src="https://cloud.githubusercontent.com/assets/22993605/20028012/47965266-a379-11e6-90ef-244a19893999.png">

**Comment by Repair-Desk** [comment]
@HafizAnas please review and assign it to @muhammadfayyaz3

**Comment by HafizAnas** [comment]
@muhammadfayyaz3 
Please have a look this issue and fix it asap. It usually happens when you refund against serialize item.

**Comment by muhammadfayyaz3** [comment]
Dear @HafizAnas I have reviewed it with @hafeezshahid and it is working fine in every scenario.

**Comment by HafizAnas** [comment]
@muhammadfayyaz3 
Problem is, as you can see in above screenshot, admin have total five serialize items and he created inventory transfer order without selecting serial, inventory stock also transferred successfully but serilize still remains in stock.
You can fix this by applying check like invoice,  system doesn't allow to create/add transfer order without selecting serials.

**Comment by Repair-Desk** [comment]
@HafizAnas @itskamran please advise updated status?

**Comment by itskamran** [comment]
@Repair-Desk It is complete, tommorow miss aishe will upload it. Thanks

**Comment by HafizAnas** [comment]
@quangc 

Your reported issue has been fixed. Kindly verify at your end do let us know if you have any question.
