### ISSUE TITLE
Issue With Receiving Inventory Against Old Purchase Order

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#86]
If you are receiving an older PO, it creates GRN with empty line items. 

**Video Link:** http://www.screencast.com/t/zCzkkkzca4Gg

**Comment by Repair-Desk** [comment]
@HafizAnas please review and report it to developer.

**Comment by HafizAnas** [comment]
@muhammadfayyaz3  Muhammad Fayyaz
I have reviewed at my end as well. There is something wrong with Create GRN against old PO. Please can you look into this and fix it asap.
