### ISSUE TITLE
Restrict Employees to view their timesheet only

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#87]
At present an employee can view hours worked and pay of other employees.

Is there a way to make it so each employee can only see their hours and time only?

![Uploading Timesheet.png…]()

**Comment by HafizAnas** [comment]
Dear @muhammadfayyaz3 
Please have a look this enhancement and provide a needful feedback.

**Comment by quangc** [comment]
This will making workplace more peaceful :D.

**Comment by Repair-Desk** [comment]
@quangc Agreed

**Comment by muhammadfayyaz3** [comment]
Dear @quangc changes has been updated. Now only superuser can filter by employees and view other employees timesheet and normal user can view their own timesheet.

**Comment by Repair-Desk** [comment]
An employee can still view Employee Payroll Report button from which he can view other employee wages **(see attached)**

![issue](https://cloud.githubusercontent.com/assets/21986026/20235587/b36d9bc8-a8b7-11e6-8daf-62018a971aa2.png)

![issue 1](https://cloud.githubusercontent.com/assets/21986026/20235595/e4a101b2-a8b7-11e6-9320-85c9f8684821.png)

**Comment by HafizAnas** [comment]
@Repair-Desk 
For now, Admin can view Payroll report of all employees but employees will be able to view only their reports.
