### ISSUE TITLE
Error on Time-sheet regarding working hours 

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#88]
Customer: Andrew Frahm (Kixup Mobile)

The working hours on time-sheet are showing more than what they really should be. For example if the Clock in is at 9:34 am and clock out is at 1:02 pm, then instead of 3.5 hours to be displayed as working hours it is showing it as 27:207. Please see the screenshot attached below for the issue.
 
<img width="1482" alt="working hours_kixup" src="https://cloud.githubusercontent.com/assets/22954033/20047369/53a8b104-a4d5-11e6-83e0-045619691c70.png">

**Comment by Fazal-RepairDesk** [comment]
The customer is facing another issue. An error notification displays when the customer tries to clock in/ out. Please see this screenshot. However I could not replicate this issue.
@HafizAnas please see if you could reproduce this error message? 
<img width="921" alt="timesheet_kixup" src="https://cloud.githubusercontent.com/assets/22954033/20047560/3dfa991a-a4d7-11e6-9abb-ca7844ff42df.png">
 attached below.

**Comment by afrahm** [comment]
The issue with the error message appears to be gone. My staff can now clock in

**Comment by Repair-Desk** [comment]
@HafizAnas please review and assign it to Fayyaz

**Comment by muhammadfayyaz3** [comment]
Timesheet updated a day ago and all issues fixed. You can check attachment as below.
![firefox_screenshot_2016-11-07t07-57-09 779z](https://cloud.githubusercontent.com/assets/22974191/20050231/e29c643c-a4e9-11e6-8a23-dc54840e1dea.png)

**Comment by Repair-Desk** [comment]
@afrahm Can you verify it on your end.

**Comment by hafeezshahid** [comment]
@muhammadfayyaz3 Working hours calculation is still wrong, hours are calculated correctly whereas the minutes are not calculated correctly. Please look into this.
