### ISSUE TITLE
Total Sales value different from Actual Sales

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#9]
The statistics page display different "total sales value" and different "location sales value".
please refer to the image attached below

![](https://cloud.githubusercontent.com/assets/21986026/19549677/12c90ba8-96bf-11e6-8a0d-f442259edd49.jpg)

**Comment by muhammadfayyaz3** [comment]
Issue Fixed and working fine on live.

**Comment by hafeezshahid** [comment]
Issue is fixed and reviewed
