### ISSUE TITLE
Application Speed Optimization

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#92]
Is there a chance we can improve speed for following:

1) Search inventory items on POS takes 30 - 60 seconds **(https://www.youtube.com/watch?time_continue=4&v=OGMl0sh7E44)** 
2) POS, Inventory Listing, Ticket Listing, Edit ticket, Save Ticket, Invoice Listing & edit invoice, login takes considerable amount of time to load.
3) Index Newly Added Database tables

**Comment by Uzair-RepairDesk** [comment]
As discussed with anas, all the possible optimizations have been completed by imran. Task will be closed now. Thanks
