### ISSUE TITLE
Tax value became positive while doing refund

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-Bugs#94]
Dear Miss @aishahanif 

Michael from CV cellular reported the following issue.

He has invoice # 2002 with total 103.19 (Price 99.99 + GST 3.20). When he did refund system took negative price but not GST and displayed total of -96.79. Invoice Number is : # 2040

I have checked it from my account. Its working fine at my end. System certainly takes negative tax value in case of refunds. But somehow Michael faced this. 
**Please find screenshot attached from his account and get it fixed.** 

![original invoice 2002](https://cloud.githubusercontent.com/assets/22955861/20089529/4edd752c-a5a9-11e6-993d-354776e1b5e5.png)
![refund invoice 2040](https://cloud.githubusercontent.com/assets/22955861/20089528/4ed626dc-a5a9-11e6-9461-e7545fe2b174.png)

**Comment by aishahanif** [comment]
@Uzair-RepairDesk  i tried many time but unable to reproduce the issue. kindly provide the steps so i can fix.
