### ISSUE TITLE
Issue with Cash Drawer

### ISSUE THREAD

**Issue by HafizAnas** [Repair-DeskPOS/RepairDesk-Bugs#95]
@Micheal st John  Reported this issue
So today has been nothing but system problems all day. My end shift was 318$ over. I did take out 480 to deposit, and used manual out to show it, but how does that even make sense. So I use manual in and put back the 480 and it says we only make 3 something but said 111 at first. How many of you guys have end shifts totals wrong quite often?

@John Wehbe also commented against this issue
My till never works properly with this system. This should be the most important feature of any POS

@muhammadfayyaz3 
I have reviewed at my end and find issue as well regarding cash Drawer. I made some transaction inwhich manual in and out also included and closed shift. According to report Closing Balance should be -100  (As you can see screenshot)
Later when I start shift again, start shift balance is different from last closing balance (See Screenshots)
Please fix it on urgent basis.

![cashdrawer-issue1](https://cloud.githubusercontent.com/assets/22954115/20091215/5f938dde-a5b3-11e6-998e-9d517b44a555.png)

![cashdrawer-issue2](https://cloud.githubusercontent.com/assets/22954115/20091222/68ed1fa8-a5b3-11e6-82a2-0f9f0d1ba9c4.png)

![cashdrawer-issue3](https://cloud.githubusercontent.com/assets/22954115/20091227/7088783e-a5b3-11e6-9b16-d7593d9db6b6.png)

**Comment by muhammadfayyaz3** [comment]
@HafizAnas issue reported by you is fixed. Let @Micheal share screens of his issues.

**Comment by micheal** [comment]
You've got the wrong Micheal. :)
