### ISSUE TITLE
Refund Button Issue on POS

### ISSUE THREAD

**Issue by HafizAnas** [Repair-DeskPOS/RepairDesk-Bugs#96]
@aishahanif 

Refund Button on POS is not working please fix this issue on urgent basis.

![refund-button-issue](https://cloud.githubusercontent.com/assets/22954115/20098654/b84f63b2-a5d6-11e6-9786-8f6627a12b33.png)

**Comment by aishahanif** [comment]
issue is fixed uploaded on both servers live (due to critical issue) and staging

**Comment by HafizAnas** [comment]
Issue has been fixed and It's working fine.
