### ISSUE TITLE
Issue with Invoice - 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-Bugs#97]
I have noticed that if you open a ticket, with various ticket items, and produce an invoice - if you want to subsequently delete the ticket and invoice, the inventory items are not re-stated back into the counts. For example:

I raise a ticket with a screen protector attached and raise an invoice

I then delete the ticket and invoice due to an error

The screen protector from this ticket should be added back to my inventory. Currently this is not the case.

**Comment by itskamran** [comment]
Issue has been resolved. Thanks
