### ISSUE TITLE
Issue with repair cost and profit not being accurate

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-Bugs#99]
I enter a screen cost as $143 and the repair cost as $199 plus tax on part. Then it says my cost is $165 and my profit is $35 and tax is $25. Then in the final report it shows my net income is $30 minus the tax $25 for some reason and that my profit is $10. Can you fix this please.

**Comment by Repair-Desk** [comment]
@jeffsand8243 can you share screenshot of report and the repair ticket. 

Also are you using trigger to charge tax on repair part only?

**Comment by muhammadfayyaz3** [comment]
@hafeezshahid can you replicate this issue your end.

**Comment by iCellsouthcity** [comment]
When you go into reports, even though we have entered the cost price for items. Some items does not show the cost price Eg: Invoice ID 3655 and invoice ID 3708
![image](https://cloud.githubusercontent.com/assets/23712887/20644542/74bdcef2-b49c-11e6-9c33-15d332bd82e1.png)

**Comment by iCellsouthcity** [comment]
![image](https://cloud.githubusercontent.com/assets/23712887/20644583/b783abf6-b49e-11e6-9baa-b68be602d5a2.png)

The system gets the sale prices wrong which is affecting the profit for that particular product for Eg: Invoice ID 3652 
The sale price is $113.04   Cost price is $45.00 (which is correct)  and GST is $14.74  Profit = $53.30

but actually the prices should have been

The sale price is $130.00  Cost price $45.00 and GST $19.5 (15%)  Profit = $65.50

So there is $12.20 diffidence in the profits.

**Comment by HafizAnas** [comment]
Hi @iCellsouthcity Thanks for sharing screenshots with us.

**Comment by HafizAnas** [comment]
@muhammadfayyaz3 
Please fix the above issue asap. @iCellsouthcity  has shared screenshots and description as well.

**Comment by itskamran** [comment]
Dear @iCellsouthcity, Issue has been resolved, Kindly check and let us know if problem still presist. Thanks
